### ISSUE TITLE
[Feature Request] Add optional Android P style task switcher

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#1341]
As Android Pies task switcher is part of the launcher it would be really cool if Lawnchair would get the option to enable this on sub-Android 9 phones.

I am confident this could work by copy pasting the code with minor changes as apps like Samsungs (Edit: For Samsung, not by Samsung) Good Lock use the same style of override on Android 8 phones.

I searched this up before and didnt find anything. If theres allready a request or a feature I'm sorry.

Good work on the app so far!
-Marten

**Comment by RikKoedoot** [comment]
Samsungs app does it because the app is allowed to by the system. In Android 9 the recents are part of the default installed launcher, not the system. But in Android versions lower than 9 it's part of the system which lawnchair can't change, copying the code from 9.0 wouldn't work as it's not supported

**Comment by suphon-t** [comment]
Before Android Pie, the recents apps view is a part of the system ui and can’t be changed without modifying it. Good Lock can do this because it’s made by Samsung and replaces the system ui.
