### ISSUE TITLE
Question: F-Droid - Upstream Source Code Not Entirely Free

### ISSUE THREAD

**Issue by 0pLuS0** [Deletescape-Media/Lawnchair#1348]
Hello,

I noticed in F-Droid it mentions this under ```Anti-Features``` in F-Droid.

The upstream source code is not entirely free

It's mentioined here on GitHub; ```Lawnchair is a free, open source``` 

Sorry, so what is this all about, in F-Droid? I thought Lawnchair is code is entirely free?

Hmm

**Comment by nyancrimew** [comment]
@0pLuS0 This is due to the Google Awareness library being used as a possible weather provider in non F-Droid builds. This library is closed source by google, thus the label on F-Droid

**Comment by 0pLuS0** [comment]
@deletescape not sure I follow the wording of ```Non F-Droid builds```?

Oh the Google Weather...

Hmm it sure would be nice if Lawnchair didn't use anything Google in it... 

And it would actually be nice if there was a Lawnchair version created without Weather, because there are plently of apps and widgets that take care of this, that we don't need something like this in a Launcher. I personally find it odd to find a weather app in a Launcher...

**Comment by nyancrimew** [comment]
@0pLuS0 Non F-Droid builds = PlayStore, XDA, GitHub or any other builds not on F-Droid
1. Lawnchair is meant to be a customizable variant of the Pixel Launcher so it is always going to be "googly" to some point
2. To get Lawnchair without any closed source Google libraries you can use the F-Droid version

**Comment by 0pLuS0** [comment]
@deletescape so why is F-Droid even saying this if the Google Awareness library is removed and it's only ```OpenWeatherMap``` in the F-Droid version?

**Comment by nyancrimew** [comment]
@0pLuS0 Because only Upstream (official Lawnchair) contains the library it is labeled as "upstream non free". As we currently haven't yet provided a flavor for F-Droid in Lawnchair itself and only their fork does so

**Comment by 0pLuS0** [comment]
@deletescape oh, so you're saying F-Droid forks it, and removes this?

By the way, this F-Droid version, I just installed it, and ```City API Key Weather Provider``` are all greyed out, I can't change the City... :(

Can you please provide a version.apk without the Google Awareness in it, here on GitHub? I think there are people like me who will appreciate this.

Thanks

**Comment by 0pLuS0** [comment]
@deletescape oh, so you're saying F-Droid forks it, and removes this?

By the way, this F-Droid version, I just installed it, and ```City API Key Weather Provider``` are all greyed out, I can't change the City... :(

Can you please provide a version.apk without the Google Awareness in it, here on GitHub? I think there are people like me who will appreciate this.

Thanks

P.S. I was looking at your blog, life shit in Lucerne? LOL I wish I could live in the Land of Swiss!

**Comment by fonix232** [comment]
Please keep the comments on-topic.

No, F-Droid does not fork us, there's a separate build config that strips the Awareness provider and related code out. We have multiple build flavours for various places, F-Droid is one of them. And I don't think it's wise to host it here, just use F-Droid for that - supposedly you already care about open-source and free stuff, thus have F-Droid installed, and using it makes things easier, especially for updates.

**Comment by 0pLuS0** [comment]
@fonix232 comments on topic, hmm, what was so off topic around here?

Anyhow, I mentioned the Weather sections greyed out, since we were talking about F-Droid builds, I didn't consider to open a bug report for it, just thought I'd mention it here...

But if you like I can, because this is broke in the F-Droid version.

Yes I like OpenSource don't you, this is suppose to be an OpenSource project...

Hmm

**Comment by fonix232** [comment]
@0pLuS0 this part:

> P.S. I was looking at your blog, life shit in Lucerne? LOL I wish I could live in the Land of Swiss!

There are a multitude of places to talk with Till about personal/non-LC stuff. Please keep the issue tracker what it was meant for: tracking issues.

This is an opensource project, meaning ALL code written by the team is opensourced. However we do use some third-party proprietary services, which we can't opensource, since they are not ours. It's still an opensource and free project, nonetheless.

As for the broken weather stuff, I think we already had a ticket open.

**Comment by nyancrimew** [comment]
Okay, so I just read through your comments again, and I think you are missunderstanding a few things here

>I personally find it odd to find a weather app in a Launcher...

There is no weather app in Lawnchair, but to provide the pixel style built in widgets including weather (just like in the Pixel Launcher we are mimicking)  we need weather data from somewhere. For this we have multiple different providers, and because the Google Awareness does this in a simple way without using more data and battery this simply provides this for users that want to use this. Everyone else is free to use the Open Weather Map provider and Lawnchair will work just as nicely, but the weather data is slightly different because they obviously use different weather providers. Users like choices so we are giving them exactly that.

If you do not want the library to be included at all that is no problem and you can use the F-Droid version or build it yourself without it. 

If there are any more questions feel free to ask in a normal manner, keeping out my personal life and mental health as it has absolutely nothing to do with Lawnchair.

**Comment by 0pLuS0** [comment]
Sorry my comments about the Blog was meant as a compliment, that's the humor where I live, saying 'wish'... Anyhow sorry taken the wrong way.

Sorry won't happen again...

I have no weather widgets or apps in the rom I am running, so I assumed Lawnchair is providing this. I only mentioned this here as a future comment, rather then making an Issue/Request to consider making a version without any weather support built into it.

As far as the F-Droid version, I mentioned that the weather app in it is broke.

Thanks
