### ISSUE TITLE
Ugly empty space between dock searchbar and icons (resubmitting)

### ISSUE THREAD

**Issue by KasraIDK2** [Deletescape-Media/Lawnchair#1381]
## Description
* RESUBMISSION: I had closed the issue when i found out there was an update to minimize padding in the works but after the update the option still didn't work so i reopened but it didn't get noticed. I'm resubmitting so maybe it would get noticed again. While we are at it, there is also another issue i have which is when i swipe up on the dock the arrow does not move until i've swiped up like half the way. Please fix this.
* UPDATE: Even after the update the option for minimal padding does not work.
* ORIGINAL: Not really sure if it's a bug or it's supposed to be there, maybe it's to do with the pie gesture navigation but to summarize there is a very ugly empty space between the searchbar and the icons in the dock. If it's something that's supposed to be there then it would be great if there was an option to remove it.

## Expected Behavior
There should be minimal space between the searchbar and icons in the dock.

## Actual Behavior
There is a big, empty space between the icons and the searchbar in the dock.

## Steps to Reproduce
No steps, but i can provide a picture showing it:
http://imgur.com/O90jZAx

## Environment
* Device: Huawei P Smart FIG-LA1
* Android version: Android 8.0.0 With EMUI skin on top
* Launcher version: v2 556 alpha build (also on latest 564 build and 571 build)

**Comment by steviator** [comment]
I'm having this bug too, I have to keep rolling back to an ancient build, I've wasted hours and hours constantly having to roll back to a months-old build and set it up from scratch every time a new build comes along because the backup and restore feature is also broken.

Perhaps the Lawnchair authors could prioritise fixing bugs rather than adding features like gestures to play despacito. 

Just a thought.

**Comment by nyancrimew** [comment]
@steviator Most of our last iteration for the latest alpha went into fixing bugs related to fixing the dock padding. the dock now perfectly matches that of the pixel 3 launcher (which yes, does have more padding to the searchbar than the pixel 2 launcher most of you are used to). An option to manually resize the dock to your liking is currently being worked on but wasnt yet functional enough to make it into our main branch for this alpha.

**Comment by steviator** [comment]
Thanks for the update, from my luxurious viewpoint of not actually looking at the code, it seems like this problem has languished for months, since nothing has visibly improved.

It's nice to hear that work is being done on this problem, I was starting to think it had been overlooked. 

I really appreciate the time and effort that has been put into Lawnchair, for me it's just a few frustrating pixels from perfection.

**Comment by KasraIDK2** [comment]
If im being honest i actually got used to it. If anything, after a while it started looking nicer to me though i still did enable the compact dock option because on default it felt like it had too much padding
