### ISSUE TITLE
Weather from Google visibility

### ISSUE THREAD

**Issue by pako-tech** [Deletescape-Media/Lawnchair#1409]
## Description

Weather from Google is visible in widget only if IN Google Weather Farenfait units are selected. No matter if C or F is chosen in Lawnchair, weather gets visible if F is selected in Google Now widget. Weather disappear if C us selected in Google Now.

## Expected Behavior

Should be visible no matter which units are selected in Google Now.

## Actual Behavior

Selected C in Google Now and Lawnchair weather is missing. Switch to F in Google Now and Lawnchair weather appears.

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device: Xiaomi Mi Max 3
* Android version: 9
* Launcher version: alpha-698
* Rom: MIUI.eu 

## Logcat

```
your log here
```

**Comment by agoNITE** [comment]
Same here. Installed alpha-698 today, no issues with alpha-689.

Mi A1, Stock Android 9.0.

I have the feeling that for me this happened since I received the new Google Discover function through Google app beta.

Edit:
Changed my device language from English (UK) to English (US), temperature from F to C again. The widget displays the correct temperature now. The issue seems to be related to your device language as well.
