### ISSUE TITLE
False Piracy Tool Detection?

### ISSUE THREAD

**Issue by zero-arc** [Deletescape-Media/Lawnchair#1423]
Hi,
I have been using your app for a while and I don't know why I can't change icon anymore and I don't know why I have a pircay app installed.

My iconpacks are also legally bought at the play store and I don't have any current piracy tool installed on my phone. So I am guessing that this is a bug or it truly detects a piracy app whatsoever.... can somebody please help?

**Comment by divadsn** [comment]
@arcenas090 It detects piracy apps such as Lucky Patcher and clones of them

**Comment by zero-arc** [comment]
I don't have that app. May I know why there is an error about a piracy tool?

**Comment by zero-arc** [comment]
@divadsn Is this a false detection as I don't see any piracy tool installed on my phone.

**Comment by zero-arc** [comment]
Hello?

**Comment by zero-arc** [comment]
Can somebody help me please?
@divadsn?

**Comment by divadsn** [comment]
@arcenas090 I will do an update tomorrow, please be patient

**Comment by zero-arc** [comment]
Thank you I just want to confirm if you are still alive and here to help.

**Comment by seankurth** [comment]
Just for anyone else who finds this thread through Google, if it ever does censor an actual pirated app from the app drawer, that is intended behavior. There's been a lot of controversy over this across social media, which the developers often end up on the wrong side of. I thought I'd clear up that while the purpose of a launcher in general is to...well, launch applications you have installed on your phone, and it can feel very shady and uncomfortable if it does otherwise, Lawnchair has another purpose that is clearly stated in its description on every app store and forum. That purpose is to replicate the Google Pixel experience as closely as possible on phones that aren't Pixels, will never have a recent enough Android version to use the latest Pixel features natively systemwide, or both. There are a few very light cosmetic customization options, but beyond that, this app can never deviate too far from stock Pixel launcher features and APIs, because a forked Lawnchair that never fully merges will become more and more difficult to backport Pixel features to as time goes on and the two continue to more widely diverge.

Guess what? Pixel Launcher censors patchers and patched apps, so Lawnchair must do so as well. If Lawnchair developers start deciding which features to leave out because they're bad, unnecessary, or annoying, and which ones are worthy of inclusion, then they can't claim to offer the Pixel experience. For better or worse, that's what users of this launcher want. If Lawnchair only offers a curated stock-like experience with a completely different base and implementations, and its only resemblance to Pixel launcher is that it's cosmetically updated to match the latest Pixel UI, then absolutely nothing would differentiate it from other launchers on the Playstore like Nova, Apex, or Rootless Pixel. Since it by design offers fewer features than those, it would certainly fail if it were yet another entirely independent third-party launcher. It would still be open-source, but most everyday smartphone users couldn't care less about software freedom, unfortunately. For those who want a stock Google-like experience, but don't care for the bleeding edge and the risks that come with it, v1 is still available in the Play Store, and will be available in the F-Droid repo forever. Other than Pie recents, there are few differences they'll notice in day-to-day use.

Personally, I support the developers' stance on protecting icon pack developers, who are typically talented individual graphic designers whose living depends on keeping their business or department going, and who rarely charge more than 99¢. Well, except for A1 Design, but you'd never need to pirate those anyway since they're always on sale for free, not that you'd ever want their incomplete, procedurally generated, and sometimes stolen/kanged crap even for free anyway. Some charge $1.99, but those offer way more than double the value of the 99¢ ones, typically exceeding OEM icon packs in their completeness, attention to detail, and professionalism. Regardless of whether or not you agree with that view, though, it must be understood that for the reasons I've already outlined, they'd still have to censor pirated apps anyway even if they didn't believe in the cause.

**Comment by fonix232** [comment]
@seankurth I think you're getting some stuff very wrong.

First of all, Lawnchair didn't censor the apps in question (or rather, did for a short while, which was then quickly removed based on user feedback), but disabled icon packs if the user is detected to be using said applications.

Since Lawnchair's only feature where we depend on possibly paid external resources is the icon pack system, this was accepted by icon pack devs who want support on fighting piracy from launcher developers, and by the dev team as well. 

However, while Lawnchair does replicate some Pixel Launcher styles and effects, it's not restricted to those. Sure, @deletescape aims to pull most features, visual or technical, but this anti-piracy stuff is something that's being removed in V2 according to my last information.
