### ISSUE TITLE
Some Icons disappear on reboot with lawnchair v2 

### ISSUE THREAD

**Issue by MadGroening** [Deletescape-Media/Lawnchair#1492]
## Description
I shut down my phone every night and on start in the morning, some icons have disappeared during the night.
it doesn't happen when i just reboot the phone. I had the same issue with rootless pixel launcher.

## Expected Behavior
the icons i configured on my home screens are there

## Actual Behavior
the icons i configured on my home screens disappear randomly

## Steps to Reproduce

1. Shut down the phone
2. wait for a while (one whole night)
3. Start the phone

## Environment
* Device: LG G6 h870
* Android version: 8.0.0
* Launcher version: alpha 2.0-1957
* Rom: V20h-EUR-XX

## Logcat

 

```
your log here
```

**Comment by nyancrimew** [comment]
@MadGroening Are those apps by any chance located on an SD card?

**Comment by MadGroening** [comment]
@deletescape yes most of them

**Comment by suppai** [comment]
I have this bug as well on my Pixel 3 XL running Android 10 and Lawnchair 2's 2019-07-20 alpha; it was introduced relatively recently, the Lawnchair 2 I was using before which couldn't have been more than a ~week old did not have the issue. 

Since my Pixel doesn't have an SD card slot and I have no external storage attached, I don't think that the issue is exclusive to apps moved to external storage.
