### ISSUE TITLE
A Hide Status Bar on Homescreen option needed to get Immersive Look

### ISSUE THREAD

**Issue by arjunraghunandanan** [Deletescape-Media/Lawnchair#1580]
## Description
Its Not a bug, Its a Suggestion
I'm into Android Development but haven't reached the skills to do much.if there is a "hide Status bar "option  for Homescreen of Lawnchair, It would be a Great immersive screen experience

## Expected Behavior
A new options should be added to the Home Edit part in the Lawnchair settings with a Toggle to Hide/show status bar on Homescreen.

## Environment

* Device:
* Android version:
* Launcher version:
* Rom:

## Logcat

 

```
your log here
```

**Comment by LuminarySage** [comment]
Can you at least glance through the settings first or even use the included settings search bar before posting an issue?

![InkedScreenshot_20190606-234034_LI](https://user-images.githubusercontent.com/24306400/59080055-c3ae9480-88b4-11e9-93a9-a72b055d0a7e.jpg)

**Comment by arjunraghunandanan** [comment]
Which Version is this?
I'm Using the latest of  play Store1.2.1.2000
and I did search through the Lawnchair desktop settings and i do not get the option which who have shown.
There is no Hide status Bar Settings in the Play Store Release ( version 1.2.1.2000)

I think i have made my sentence clear, haven't i?

**Comment by arjunraghunandanan** [comment]
![photo_2019-06-08_02-17-26](https://user-images.githubusercontent.com/42718953/59132731-9d135b00-8993-11e9-8584-c41ff9ad820d.jpg)
![photo_2019-06-08_02-19-45](https://user-images.githubusercontent.com/42718953/59132859-e794d780-8993-11e9-8f17-1e6bdec931d3.jpg)

**Comment by LuminarySage** [comment]
You do realize you are reporting bugs in the Lawnchair V2 repository right?

**Comment by LuminarySage** [comment]
The Play Store version is deprecated from a long time ago (yes I know it recently got an update in May but that was just a security patch). Just so you know, you came all the way to Github to report an issue without even glancing at the front page to see if you're in the correct repo or not...

![image](https://user-images.githubusercontent.com/24306400/59140678-e2716180-896e-11e9-976f-24507c50b753.png)

Anyways, either get the latest V2 alpha release from [here](https://www.apkmirror.com/apk/deletescape/lawnchair/) or wait until Lawnchair V2 hit Play Store. Close this issue because it's not applicable to V2 and because V1 won't get feature updates anymore.
