### ISSUE TITLE
Folders in dock wont respect icon size option.

### ISSUE THREAD

**Issue by arttuc** [Deletescape-Media/Lawnchair#1827]
## Description

I have set the icon size in the dock to 120% but folders just stay at 100%. I have tried restarting, withour cover mode, making new folder after option changed. still stays at 100%

## Expected Behavior

Folder icon changes size like normal icons do.

## Actual Behavior

Only the normal icons change size, folders don't.

## Steps to Reproduce

![Screenshot_20191122-095438_Lawnchair](https://user-images.githubusercontent.com/37794543/69408393-6f3a8c80-0d0f-11ea-85ad-7cc9d9c39256.png)
left is normal icon, right is folder in cover mode. both have same icons.
1. Set the dock icon size to something bigger than 100%
2. Create a folder in the dock, normal or cover.

## Environment

* Device: Pocophone F1
* Android version: 9.0.0
* Launcher version: 2.0-2551 (play store beta)
* Rom: LineageOS 16 Official

**Comment by rydwhelchel** [comment]
I have the exact same issue as here. Below you can see the joystick icon is much larger than the other icons, and is getting cut off because of it.
![image](https://user-images.githubusercontent.com/58048729/69442923-6485f480-0d1b-11ea-8181-6d6b1dfc5379.png)

**Comment by omgwtfbbqpls** [comment]
Same issue on LOS16. 
The actual problem is that folders on the dock follow the size of the desktop icons, not the dock icons. Please fix :(

An additional issue - if the desktop icons and dock icons are set to be the same size (e.g 50%), and the launcher is rotated to landscape, then the folder icons have part of their left and right sides cropped off. 
It seems there's a related issue https://github.com/LawnchairLauncher/Lawnchair/issues/1998 which can affect all dock icons, not just dock folder icons.

**Comment by koutheir** [comment]
Same issue on Android 11. Any ideas how to fix this?
