### ISSUE TITLE
[FR] Ability to add apps manually in automatic categorization in tabs

### ISSUE THREAD

**Issue by subediaayush** [Deletescape-Media/Lawnchair#1862]
Is there a way to add apps manually in automatic categories? Automatic categories are great but do not recognize all apps for a given category. It would be best to automatically add apps to categories and later allow users to assign app into those categories.

**Comment by chdlc** [comment]
Sorry, but where is the option to enable the auto categorization? Thanks in advance.

**Comment by subediaayush** [comment]
> Sorry, but where is the option to enable the auto categorization? Thanks in advance.

You can find it in Settings > Drawer > Categories
Enable categorize apps, select tabs style, the create new tab and select Automatic

**Comment by mnaxx** [comment]
This is a much needed "feature fix" because "auto-sort" isn't good enough on it's own, It misses a couple everytime, So I have to manually make tabs and it's a nightmare Everytime, because auto-sort is close but not close enough because I can't add anything to it. See what I'm saying? It'd be much better being able to modify automatic tabs on the user end only. I think the solution might be adding a blacklist/whitelist to custom tabs, if anyone wanted to give it a try.
