### ISSUE TITLE
[FR]Blur effect for live wallpaper

### ISSUE THREAD

**Issue by ongsalt** [Deletescape-Media/Lawnchair#1892]

**Comment by DanGLVK** [comment]
@o-ngsa Not possible, live blurring is simply too demanding to do at a steady 60fps

**Comment by SkyyySi** [comment]
Have you reconcidered it? You could also just make it an option ("Enable live wallpaper mode (power hungry)"), so if you don't want it or your phone cannot handle it, just turn it off. However, since many vendor roms (like MiUI or OneUI) have fullscreen blurring in multiple places, I can't imagine that it would be _that_ bad on a somewhat modern phone. Actually, on Android 11, every wallpaper is (kind of) a live wallpaper: If you pull down the quick settings, it zooms out. Which can really brake the effect in my opinion.

**Comment by DanGLVK** [comment]
The thing is, when OEMs implement blur they get to add their optimized algorithm into the Android framework, unfortunately AOSP (at least up to Android 10) lacks an efficient blur rendering method, most blur techniques/libraries on apps are currently static as they rely on taking a screenshot, blurring it and storing it in memory, doing that on a live wallpaper would be suicide (even in high end phones) for the current blur libraries we have available

**Comment by SkyyySi** [comment]
Really? Ok that makes sense. Running multiple compositors at the same time would probably cause issues (if possible at all). Testing out 5 diffrent librarys would probably be asking for too much here. Just out of interest, is it possible to use the vendor's  blur API? Shure, this would suck for stock-like rom users (like me, who uses a Pixel), but I guess it'd be better then the current solution. We should really try to convince google to add a native blur API that can be expected to be on a device, though I don't think they'll do it anytime soon.

**Comment by suphon-t** [comment]
It’s not only about power. Android prevent apps from even accessing the output of live wallpapers. So we can’t do it even if we have enough GPU performance.

**Comment by SkyyySi** [comment]
Oooh so that's why every launcher with blur I tried just showed transparency. Because that's all it can show without screenshoting the entire screen - which simply would not work. Thank you for explaining. Although it's kinda odd how OneUI (the launcher) can apperantly do it, but then again, there's no way of nowing what samsung has made with their rom, so they probably added some kind of exeption or something like that.

**Comment by DanGLES3** [comment]
> Oooh so that's why every launcher with blur I tried just showed transparency. Because that's all it can show without screenshoting the entire screen - which simply would not work. Thank you for explaining. Although it's kinda odd how OneUI (the launcher) can apperantly do it, but then again, there's no way of nowing what samsung has made with their rom, so they probably added some kind of exeption or something like that.

As said, OEMs can easily mod Android to allow for such things for their system apps

**Comment by pxrakeev** [comment]
Nice

**Comment by pxrakeev** [comment]
Nice
