### ISSUE TITLE
Unable to search in drawer on 2.1-2616-ci-q-pre-alpha

### ISSUE THREAD

**Issue by Reprevise** [Deletescape-Media/Lawnchair#1935]
## Description

I installed the update this morning when I got the alert from Telegram and I was able to use my search box at first but then I kept getting IndexOutOfBounds exceptions that crashed the launcher. I've tried removing custom icons and deselecting all of my icon packs and nothing helped.

## Expected Behavior

When you search, it should start filtering out apps that don't meet the query.

## Actual Behavior

As soon as you start typing, the launcher crashes.

## Steps to Reproduce

1. Open drawer
2. Search anything
3. Launcher crashes

## Environment

* Device: Samsung Galaxy S10
* Android version: 10
* Launcher version: 2.1-2616-ci-q-pre-alpha
* Rom: One UI 2.0

## Logcat

 

https://del.dog/ebatabylyd.txt

**Comment by tgt26** [comment]
I am experiencing the same issue. However, I think know what's causing it to crash. I have a couple of apps hidden from the app list. If I try to search for an app and one of the hidden apps share the first letter then the launcher crashes. 

For example: I have Facebook hidden but Football Tracker (just a random name) not hidden. If I type the letter "f" on the search bar, the launcher crashes. 

It might be caused by something else, though.
