### ISSUE TITLE
No notification access for Android (go edition) devices [Maybe ADB]

### ISSUE THREAD

**Issue by alvindera97** [Deletescape-Media/Lawnchair#1952]
## Description

On Android Go edition devices, there is no Notification access support for third party apps. Only special apps especially Google's are given notification access if needed. This is basically how Android Go Edition was designed to operate. However because of this design limitation, there is no notification access support either. 

## Expected Behavior

When the "Change settings" button is clicked when the app displays the box saying "Notification access needed", another lawnchair app page is opened and visual cues are pointed at the Notification Dots setting. Clicking this button however takes the user to a system notification settings page where there is an option to change the notification dots setting.

## Actual Behavior

When the "Change settings" button is clicked when the app displays the box saying "Notification access needed", another lawnchair app page is opened and visual cues are pointed at the Notification Dots setting. Clicking this button however takes the user to a system notification settings page where there is no option to change the notification dots setting

## Steps to Reproduce

1.
2.
3.
4.

## Environment

* Device: Nokia 2.1
* Android version: 9.0 (Go edition)
* Launcher version: 2.0-2589
* Rom: Stock Android

**just for note.... I was hoping that notification access can be granted to Lawnchair using ADB. I would greatly appreciate it if you could provide the particular ADB command**

## Logcat

 

```
your log here
```

**Comment by alvindera97** [comment]
I guess I'll have to reopen this issue as it has not been solved and I just got an update on the situation at Lawnchair.

**Comment by ghost** [comment]
@alvindera97 here's a bit more info on what's going on: https://twitter.com/lawnchairapp/status/1261022920111009800

**Comment by alvindera97** [comment]
@LPW00 Thanks for the update.... I really didn't know anything about their break,.... Besides, it's been a while since I posted this issue. **A very long while to be precise.**

**Comment by ghost** [comment]
@alvindera97 Well, the last public release was in February, according to my knowledge, so a tad older than your issue. It's really been a long hiatus.

Additionally I've had a phone with Android 9 Go and I think notification access for 3rd parties is just not something it offers and lawnchair can't really change that. Neither have I seen any other app that's able to do that. So that might be another reason you've got no response.

If you know how to do that or can provide with an open source app that does that, maybe that feature can be put on the list of things to implement, once development picks back up or you or someone else can do a pull request.

DISCLAIMER: I'm not a developer.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11
