### ISSUE TITLE
double tap to sleep ask for accessibility permission repeatedly

### ISSUE THREAD

**Issue by Laikos38** [Deletescape-Media/Lawnchair#1953]
## Description
Double tap to sleep ask for accessibility permission repeatedly. The only solution it seems to be reboot the phone, but in a few minutes its ask for accessibility permissions again.

## Expected Behavior
If I double tap it should lock the screen.

## Actual Behavior
When I double tap it gets me to the accessibility menu in configurations.

## Environment
* Device: Pocophone F1
* Android version: Android 10.
* Launcher version: Lawnchair v 2.1-2616
* Rom: Stock, with MIUI 11.0.4 (Global)

**Comment by DanGLVK** [comment]
@Laikos38 That's happening because MIUI is constantly killing our accessibility service which causes it to get disabled, make sure to whitelist lawnchair from MIUI's optimization  https://dontkillmyapp.com/xiaomi

**Comment by Laikos38** [comment]
Hi, I followed the steps in the link and enabled the admin permission for the app in Settings -> (search admin) -> device admin apps and I got it to work perfectly fine now. Thanks!

**Comment by AdityaMitra5102** [comment]
Same thing in Galaxy M30s OneUI 2

**Comment by steviator** [comment]
This should not be closed this is still happening on Moto G8 Power and Samsung J6 with battery optimzations off, accessibility service enabled and device admin turned on.

Other apps like Macrodroid have no problems keeping their accessibility service working or turning the device off using admin mode, this is entirely a lawnchair bug and seems to be present on most devices.

Please fix this bug instead of pretending it doesn't exist.

**Comment by nalladev** [comment]
https://github.com/LawnchairLauncher/lawnchair/issues/2081#issuecomment-3588656848
