### ISSUE TITLE
Folder Drawer View - Choppy Animations

### ISSUE THREAD

**Issue by andeke07** [Deletescape-Media/Lawnchair#1993]
## Description

My OnePlus 6 running Android 10 exhibits choppy animations when I have Lawnchair in folder mode rather than category mode. The phone is otherwise snappy, it is just the revealing of the drawer, and opening/closing of folders that is choppy.

## Expected Behavior
Animations should be smooth

## Actual Behavior
Drawer reveal and folder open/close animation looks choppy. When it's happning, it looks like my phone is suffering from significant performance lag, but all other phone animations/app response is quite snappy

## Steps to Reproduce

1. Put Lawnchair in to folder organization mode
2. Put apps in to folders
3. Swipe up to reveal drawer
4. Open/close folders

Here is a video, however it looks smoother in the recording than it does in real life: https://drive.google.com/file/d/15i79zMOa0g5bTY-o_TScR_RBJgTlTonA/view?usp=sharing

## Environment

* Device: OnePlus 6
* Android version: 10
* Launcher version: 2.0-2589
* Rom: OxygenOS 10.3.2

**Comment by login0false** [comment]
Also have this issue on a different device (Mi 9T, MIUI 11, Android 10), so it's not just you.
By the way, only the launcher is affected - system animations (like pulling down notification shade) that happen over the problematic screen are smooth. Also, if I scroll further down into the drawer so that the folders are no longer visible, the frame rate returns to normal and scrolling becomes smooth again.

**Comment by andeke07** [comment]
Someone opened 1994 after me, it looks like this is related to icon shape, changing icon shape to circles makes the folder animations faster.
