### ISSUE TITLE
Android 11 - Home button / pill is shown constantly

### ISSUE THREAD

**Issue by chudobsn** [Deletescape-Media/Lawnchair#2051]
## Description
* The home button / pill is shown on every screen, even at the ambient screen. 
* When switche the rotation, sometimes the pill will be stucking at the side and Lawnchair has to be restarted or / and switched back to Pixel Launcher and back to Lawnchair.

## Expected Behavior
* Should be hidden as expected.
* When roatate the display, should be also moving with the rotation.

## Actual Behavior
* Will not hide the home button / pill automatically as before 
* Did not move together with the display rotation.

## Environment

* Device: Google Pixel 4 
* Android version: Android version: 11 (RP1A.200720.009)
* Launcher version: 2.10-2589

**Comment by TheFancyDinosaur** [comment]
I encounter the same issue. It becomes really annoying when in Landscape mode because the side where the bar/pill is located the touch gestures don't work as if there was a invisible bar covering the whole edge.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11

**Comment by StevenAlexander44** [comment]
Has this been implemented yet? I still have the same issue

**Comment by DanGLVK** [comment]
> Has this been implemented yet? I still have the same issue

Does this happen on other third party launchers as well? (kindly test it if possible) Because if that's the case then it might be a system issue which is beyond our ability to solve 

We are currently not aware of a way to hide the navigation pill on the homescreen (without root) that doesn't mess with gestures somewhat

**Comment by StevenAlexander44** [comment]
Using the default moto app launcher this doesn't happen, and I found that a temporary fix is having auto-rotation on, and I think the Lawnchair option for home screen rotation also has to be on too

**Comment by DanGLVK** [comment]
K

> Using the default moto app launcher this doesn't happen, and I found that a temporary fix is having auto-rotation on, and I think the Lawnchair option for home screen rotation also has to be on too

Which is why I've asked you to check other third party launchers, if this is a system bug then there isn't much we can do

**Comment by StevenAlexander44** [comment]
After some testing I've found that the app has to be launched in landscape mode for the pill to go away and function normally. I'd be ok with this inconvenience if its too hard (or impossible, without root) to fix.

Also Lawnchair is the first non default launcher I've ever used, so I don't know of 3rd party alternatives to try.
Oh and another sidenote VLC doesnt have this issue for some reason- possibly because the app works both in landscape and portrait mode.

Thanks for your help 🙂
