### ISSUE TITLE
Vertical recents screen?

### ISSUE THREAD

**Issue by GottemHams** [Deletescape-Media/Lawnchair#2185]
I believe since Android 9 the recent app screen (or Recents, Overview, whatever they call it nowadays) has had a horizontally scrolling layout. Is it at all possible to turn this back into the vertical one from before? I noticed you managed to put the `Clear all` button from all the way to the left (whoever thought that was a good idea?) to below the app windows, so perhaps reorienting the screen would be possible too?

**Comment by DanGLVK** [comment]
While technically feasible it would be a lot work to completely modify the look and behavior of quickstep to allow a vertical scrolling recents, and right now focus is on bringing back older features, so maybe in the future this may be considered

Also about the clear all button, Google had purposefully moved it to the far left with the intent of discouraging people from using it (as they consider it an overkill option that offers little to no benefits) it was only moved down on Lawnchair due to constant user request to make it accessible, if and when you choose to use it is up to your personal discretion

**Comment by GottemHams** [comment]
Fair enough. Then, could you maybe tell me how to even create a custom (QuickSwitch-compatible) recents screen? I might try my own hand at it. :> I find Android's documentation quite lacking in most areas and I'm not familiar enough with custom launchers to figure it out myself within a reasonable time. I do have a lot of experience with regular apps though.

>as they consider it an overkill option that offers little to no benefits
I dunno, I find it pretty handy to get rid of all apps at once and have a clean screen. Like when you're trying something out you can easily have at least a dozen "open" apps, manually flicking them off the screen every time is quite a hassle.

Anyways, not really important since it wasn't even your decision to move it in the first place. =]
