### ISSUE TITLE
Add individual icon customization

### ISSUE THREAD

**Issue by OxygenCobalt** [Deletescape-Media/Lawnchair#2201]
Back in Lawnchair 2 [or 10], you could set the icon of an individual app in the launcher by long-pressing on it and then pressing the edit button. In the Lawnchair 11 alpha, it seems like this option is not present and you can only apply icons to every app. 

This is a problem for me since some of my apps [mostly the proprietary ones] can't be applied by the monochrome icon packs that I like to use, which results in less stylistic cohesion. I don't like using system icons since their colorful nature can be very distracting and hard to read.

I know Lawnchair 11 is still in alpha, but is this being planned?

**Comment by vaisakhv** [comment]
Even if an alternative icon is there in the current icon pack users are unable to replace the current icon with the alternative one since the option is not there in the latest alpha builds.  This is becoming a primary reason to switch to an alternative launcher like Nova or roll back to lawnchair v2. Please bring back this option.

**Comment by 1-minute-to-midnight** [comment]
I'm waiting for this feature to switch to lawnchair 12

**Comment by DanGLVK** [comment]
> I'm waiting for this feature to switch to lawnchair 12

It is already available in Lawnchair 12 Alpha 5 as an experimental feature (in settings tap the 3 dot icon in the top corner)

**Comment by 1-minute-to-midnight** [comment]
Thanks a lot!!!!

**Comment by vaisakhv** [comment]
Thanks for the update
