### ISSUE TITLE
Simplified Chinese is incorrectly displayed

### ISSUE THREAD

**Issue by mdogwoop** [Deletescape-Media/Lawnchair#2207]
The language set on my phone is simplified Chinese, but the language it displays is traditional Chinese
![Screenshot_20210819-124636_Lawnchair.png](https://user-images.githubusercontent.com/64186089/130009434-55104326-d344-4c4b-97b4-95997ec71cbf.png)

**Comment by mdogwoop** [comment]
This seems to be a matter of desktop settings, other interfaces seem to be in simplified Chinese.

**Comment by RikKoedoot** [comment]
This might be a translation error, you can fix them at https://lawnchair.crowdin.com/lawnchair (our translations are publicly sourced)

**Comment by FrzMtrsprt** [comment]
It's not a translation error, since the strings in Crowdin are correct. The entire Lawnchair settings is displayed in zh_TW, even if I set my device language to zh_CN or zh_CN_#Hans. This problem is still present in the latest Lawnchair 12 nightly version [#593](https://github.com/LawnchairLauncher/lawnchair/actions/runs/1425604599)

**Comment by FrzMtrsprt** [comment]
And 12.0 Alpha 4

**Comment by SuperDragonXD** [comment]
Very late reply, but as said by Patryk in `#2360`, it has been fixed in https://github.com/LawnchairLauncher/lawnchair/commit/9879b59ff1c7b56f981c1e6da6a5baf5e8321637. Update to Lawnchair 12 Alpha 5 (or if it still isn't working, the latest version: 12.1 Alpha 3) to fix this issue.
