### ISSUE TITLE
When swiping up from the bottom with the dock enabled, the dock opens while switching apps.

### ISSUE THREAD

**Issue by StarrKiss** [Deletescape-Media/Lawnchair#2248]
This is nothing more than a visual glitch that also takes up a bit of time. but using the new Pixel gesture navigation, if I swipe up from the bottom halfway to open the app switcher, it also opens up the drawer at the bottom of the dock, which looks super odd. The same issue happens when returning to the home screen from the app. I wish there was a way to create a "swipe deadzone" at the bottom of the screen so that any swipe that STARTS there would be ignored, thus I could swipe from the gesture bar and it'd work fine. As it is I am considering switching off of lawnchair because it's so ugly and annoying.

**Comment by RikKoedoot** [comment]
(I'm assuming you're a quickswitch user) The dock showing there is to be expected as it is (until android 11) how pixels work. In gestures settings you can change the "swipe up from dock" gesture to "do nothing" if you don't want that to happen.

**Comment by RikKoedoot** [comment]
I will be closing this issue as it's related to a legacy version of lawnchair, we are working on v11 to become the main lawnchair version and won't be focusing development effort on the older versions.

**Comment by StarrKiss** [comment]
> (I'm assuming you're a quickswitch user) .

Not using quickswitch, just the stock Pixel switching. I want the dock to show, I don't want the drawer to open when I return to the homepage immediately, however. The stock pixel launcher has an identical way to open the drawer and yet it doesn't open on return to home page.

**Comment by RikKoedoot** [comment]
This is due to how android works. The recents screen is part of the pixel launcher. If you are using a third-party launcher with it, it won't show the apps at the bottom, because it can't get those from another launcher. 
Same goes for the swipe up thing, if you use lawnchair, and swipe up via the dock, we cannot make it fluently go to recents because it's not part of our app. 
And about the appdrawer closing when going home, this is a known issue and I'll see if it's present in v11 and inform the developers about it if it's still an issue
