### ISSUE TITLE
Swipe up to open app feature

### ISSUE THREAD

**Issue by CHanoey145** [Deletescape-Media/Lawnchair#2285]
Swipe up to open app, set shortcuts. Add the feature into the new version

**Comment by themooleman** [comment]
I'd love to see this feature added. I currently use Lawnchair 2 from the Play Store purely because it supports this feature. I love having all of my shortcuts be two shortcuts. It makes it so much faster to launch apps and I'm reluctant to use a launcher which doesn't support this... Otherwise, Lawnchair is fantastic and I'd like to be using it rather than an outdated fork.

**Comment by CHanoey145** [comment]
Request devs to provide this function in the new version. I'm still using the order version because of this particular function

**Comment by themooleman** [comment]
> Request devs to provide this function in the new version. I'm still using the order version because of this particular function

As am I.

**Comment by themooleman** [comment]
Keeping this fresh. I'd still love to see this feature.

**Comment by themooleman** [comment]
Keeping this fresh. Still really keen on this feature.

**Comment by ghost** [comment]
Bro's dedicated to keeping this feature request alive 💀💀💀

**Comment by themooleman** [comment]
Now I just need to learn Android development so I can actually do something
about it...

**Comment by CHanoey145** [comment]
Keeping this fresh

**Comment by ghost** [comment]
Mhmmm, I'll join



Also keen on this feature, keeping this fresh!

**Comment by bappitybup** [comment]
would also like this 👍

**Comment by ghost** [comment]
Also like this! (again lol)
