### ISSUE TITLE
Glitchy closing app animations

### ISSUE THREAD

**Issue by alejandro097** [Deletescape-Media/Lawnchair#2293]
I don't know if it is supposed to be like that, but looks kinda buggy to me.

A11 Alpha6.1 (normal behavior ig)
https://user-images.githubusercontent.com/47724370/139601109-61ec1d1e-3c23-4b8c-83f8-5989824aaa6c.mp4

A12 Alpha2 (the Icon goes outside when it should be hidden behind the "recent screen")
https://user-images.githubusercontent.com/47724370/139601142-704a35d3-67a5-4c50-871d-91bf31915f69.mp4

**Comment by SuperDragonXD** [comment]
Late reply, but it seems to be more or less intentional since A12 has a redesign of the Recents screen, removing the translucency effects. Then again, it may be different depending if you have QuickSwitch or not. If you do have it, it is intentional. Otherwise, it's an issue with many third-party launchers. Also closing due to this relating to an older version of Lawnchair. (we no longer support old versions)
