### ISSUE TITLE
Question: Why are the number of Settings decreased since Lawnchair 11?

### ISSUE THREAD

**Issue by contourintegrals** [Deletescape-Media/Lawnchair#2298]
Pretty much the title. 

I wanted to try Lawnchair 11 because I got LineageOS 18.1 on my device, so I tried the latest Alpha version. In it, I noticed that the Settings didn't have the options I usually wanted to customize. Back Up & Restore wasn't on it either. Why is that? I currently use Lawnchair 10, because it does contain those settings. I really want to try Lawnchair 12 because of it's Material You and '`monet`-like' update, but the reduction of Settings bothers me.

Sorry if this is already asked.

**Comment by GEkuL** [comment]
1) don't use github issues if you have such general questions. There's Telegram group for that
2) they've decided to rewrite the whole all since Lawnchair 10 and drop 10th version in favour of 11-12.

So it seems like all the features will be rewrited as well. And for now the essential backup/restore feature is out :(

Hopefully devs will bring it back soon.
As for other features, they'll be restored in some time.

**Comment by msfjarvis** [comment]
Questions belong on the Telegram group as mentioned. Keep the issue tracker strictly limited to specific bugs please. Features will make their way back in due time.
