### ISSUE TITLE
QuickSwitch (Lawnchair 12) (Android 10)

### ISSUE THREAD

**Issue by andr0d1v** [Deletescape-Media/Lawnchair#2346]
Please do so that you can put lawnchair 12 for android 10 in QuickSwitch!
![Screenshot_20211128-135458158](https://user-images.githubusercontent.com/87223939/143771807-a8eec909-160f-48ba-838c-6d233c12f39f.jpg)

**Comment by SuperDragonXD** [comment]
Late reply, but it's highly unlikely that support for A10 will be given, since Lawnchair 12 is a rewrite from Launcher3 from Android 12, and they'll need to port many stuff in order to make it support A10, and some APIs may be different depending on QS versions, and they'll likely need to rewrite some stuff. Therefore, closing this issue. (also partly since this is relating to Lawnchair 12)
