### ISSUE TITLE
[Meta] What happened to all the features? 

### ISSUE THREAD

**Issue by onkoe** [Deletescape-Media/Lawnchair#2367]
Hi! I've been using Lawnchair for about three years now. However, after a couple of years without an update, I realized that it's once again in active development. After reading through a decent amount of the development materials, though, I still have one question: where did all the features go?

I'm missing a ton of features from Lawnchair 2 in newer versions. I'll give a short list below:
- Search widget
- At a Glance customization
- The AWESOME camouflaged folders (cover mode, allowed me to use multiple email clients without looking like a nerd) 
- Layout backups/restoration
- Some icon shapes
- Stable releases :(

This isn't to demand anything from the development team; this is a great FOSS launcher, even without these features. That said, though, where did all of these features go? Does it have to do with the AOSP launcher (Launcher3) removing them? Many thanks for your development and support time!

**Comment by DanGLVK** [comment]
Lawnchair 11 (And now 12) were rebuilt entirely from scratch, so every single feature is now having to be reimplemented on the newer (and cleaner) codebase

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
- cover mode!
Yes that was the greatest feature since gel xpose Mod

For any testers and Alpha version tester more importantly feature is
- Layout backups/restoration


Previously it even worked flawless between different devices

Does those exist in any secret hidden v10 version that is not public release? It seems all hidden. I try both V12 and v11 and deleted immediately because found both useless as missing the basic features of lawnchair not limited to above mentioned.

V12 & v11 is downgraded.

V9 alpha still have it. But I cannot even find any v9 Version anymore?

So did V10 exist with feature set or also limited?

**Comment by takkuso** [comment]
I would also like to request cover folders!

**Comment by omentic** [comment]
I would like to request the reimplementation of swipe-up-to-play the first fifteen seconds of YouTube Rewind (2018). Simply the greatest feature, Lawnchair just isn't the same without it.

In all seriousness: congratulations on the mostly-stable alpha release!

**Comment by SuperDragonXD** [comment]
The launcher was rebuilt as stated by [DanGLES3](https://github.com/DanGLES3). Therefore some features are not re-added yet. Some features have been re-added in Lawnchair 12.1 Alpha 3 though, like:
* Search widget
* At a Glance customization
* Layout backups/restoration (incompatible with v2)
* Some icon shapes
* Stable releases (Alpha is mostly stable now)

Will close this issue due to most of your requests being fulfilled.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> Hi! I've been using Lawnchair for about three years now. However, after a couple of years without an update, I realized that it's once again in active development. After reading through a decent amount of the development materials, though, I still have one question: where did all the features go?
> 
> I'm missing a ton of features from Lawnchair 2 in newer versions. I'll give a short list below:
> 
>     * The AWESOME camouflaged folders (cover mode, allowed me to use multiple email clients without looking like a nerd)
> 


Yes, the feature exist in Lawnchair Legacy version 9.1 alpha 3

The missing “camouflaged folders” mentioned here seem to correspond to the Cover Mode reimplementation currently tracked in #2659.

- #2659
