### ISSUE TITLE
Add support for Android 7.0

### ISSUE THREAD

**Issue by GloopSee** [Deletescape-Media/Lawnchair#2412]
Please add support for Аndroid 7.0

**Comment by z0xrv** [comment]
Will the developers tell us the status or close this issue?

**Comment by SuperDragonXD** [comment]
Having support for Android 7.0 is very unlikely due to: Android 7 being unsupported; APIs only available to later Android versions; and only 4.5% of all Android users have Android 7.0, which makes support for them not really important.

I'd recommend updating your device, or simply buying a new device with a newer Android version. And yes, closing this issue too.
