### ISSUE TITLE
Lawnchair crash due to secondary screen.

### ISSUE THREAD

**Issue by Kalpu-24** [Deletescape-Media/Lawnchair#2421]
When i attach my device secondary screen it crashes.
I have LG G8X.
Here is the crash log.
[Lawnchair bug report 15 Jan 2022 40415 pm.txt](https://github.com/LawnchairLauncher/lawnchair/files/7874810/Lawnchair.bug.report.15.Jan.2022.40415.pm.txt)

**Comment by SuperDragonXD** [comment]
Unfortunately, the secondary screen will not work with Lawnchair as the default home app (unless you have QuickSwitch). Besides that, it has been removed in the later releases due to being very buggy too. You can try making the system launcher the default temporarily to fix this. Closing this issue.
