### ISSUE TITLE
compilation request

### ISSUE THREAD

**Issue by ACHOKAMAN** [Deletescape-Media/Lawnchair#244]
please add this features soon,
1.icon mas design like square just like O pixel launcher.
2.folder design.
3.backported features to <7.1
4.scrolling wallpaper.
MAJOR FEATURE;
5.ABILITY TO IMPORT DESKTOP CONFGURATION FROM ANOTHER LAUNCHER..

**Comment by AxiK101** [comment]
Nice said 😋

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Treemindr** [comment]
2. What do you mean?
4. That's already built in and it works just fine.

**Comment by one17dev** [comment]
I believe #5 is already built in. 

_Sent from my Android XT1575 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fonix232** [comment]
1. Work on the adaptive icons, including custom icon masks (circle, squircle, rounded rectangle, teardrop, etc.)
2. Please go into detail. Two words do not say the exact thing you want.
3. Features are already backported...
4. This is being considered too
5. Doubt that this is a good idea, since launchers have different layouts (5*6, 4*5, etc.), and transformation requires quite a lot of work on the logic.
