### ISSUE TITLE
Dragging apps across home screen has UI pushed up off the screen

### ISSUE THREAD

**Issue by PeterNjeim** [Deletescape-Media/Lawnchair#2444]
When using Windows Subsystem for Android (WSA), I'm getting a glitch where if I drag an app that is on the initial page or in the app drawer (even if I'm on the second page then open the app drawer, the issue persists), the UI will move up: 
![image](https://user-images.githubusercontent.com/26418974/151720632-05968ab5-3463-4057-bce6-88e667a7b27c.png)
![image](https://user-images.githubusercontent.com/26418974/151720714-e2064b4b-ebcf-4fbf-ae3d-4b79518f0b0e.png)
even when dragging the app to the second page: 
![image](https://user-images.githubusercontent.com/26418974/151720705-3824ffcd-2d6c-4f79-a95f-6e81b4b54d86.png)

If I move an app that was originally on the second page, there will be no glitch, even if I drag it to the first page: 
![image](https://user-images.githubusercontent.com/26418974/151720657-3805077d-ee47-4c01-907f-176bf3a4e36a.png)
![image](https://user-images.githubusercontent.com/26418974/151720748-34734807-5fa9-4132-a87b-1077666035a1.png)

This might be due to the patch I made here: #2373, but I'm not sure. Also that glitchy line at the bottom of some of the screenshots is not present in reality, looks like a Windows screenshot bug.

**Comment by PeterNjeim** [comment]
That's not how "closing" issues works. Closing an issue means it's either: resolved, a duplicate, invalid, or not planned. In no situation should a bug report be closed simply because it hasn't been dealt with for an arbritrary number of days.

**Comment by PeterNjeim** [comment]
Also your bot falsely said it would close it in 14 days, when in actuality it closed it in 9 days, and then falsely claimed that it had only been 7 days.

**Comment by PeterNjeim** [comment]
At the very least, change the bot so that when it closes stale issues, it'll close them as "not planned", instead of "completed", because it's misleading

**Comment by yasanglass** [comment]
We just updated the stale config to close after 7 days. 

Closing the issues is done to clean up the issues that are not relevant anymore or/and not enough people ask for. And we always can & sometimes do "fix" issues that have been already "closed" here.

This issue is a good example of a stale issue actually as only a handful of people use Lawnchair on WSA and as a result, not enough people care about this issue to make fixing it worth the developers' time.

Its not misleading because anyone literally can read the stale bot' comments, but ill close it as not planned just for you.
