### ISSUE TITLE
showing error in systemui-shared

### ISSUE THREAD

**Issue by Ashwin-DevAsh** [Deletescape-Media/Lawnchair#2459]
import android.util.IconDrawableFactory;
                   ^
  symbol:   class IconDrawableFactory
  location: package android.util

which gradle version should i use ?

**Comment by ghost** [comment]
Hello! Have you selected the `lawnWithQuickstepDebug` build type? As for the Gradle version, I suggest you use the one defined in the project files.

**Comment by Ashwin-DevAsh** [comment]
yup i thried that too....

import android.util.IconDrawableFactory;
^
symbol: class IconDrawableFactory
location: package android.util

do you know why this error throwing in system-sharedui

**Comment by ghost** [comment]
I’m afraid it’s hard for me to say, because I’m not familiar with your development setup. Perhaps you haven’t cloned the submodules required by the project? Try running `git submodule update --recursive`. With the submodules downloaded and the `lawnWithQuickstepDebug` build type selected, you should be able to build Lawnchair. Please see [here](https://github.com/LawnchairLauncher/lawnchair/blob/12-dev/.github/workflows/build_debug_apk.yml) for the GitHub Actions workflow that successfully builds Lawnchair.

**Comment by Ashwin-DevAsh** [comment]
hey i found where the issue is : 

   **kotlinOptions {
        jvmTarget = '1.8'
    }

    addFrameworkJar('framework-12.jar')**

 addFrameworkJar is not working.... could you explain about addFrameworkjar.... i couldnt find the documentation also

**Comment by msfjarvis** [comment]
> addFrameworkJar is not working.... could you explain about addFrameworkjar.... i couldnt find the documentation also

You can easily search for it in the repo and find its definition [here](https://github.com/LawnchairLauncher/lawnchair/blob/69c1e12cbaa55a784ebf2378f0bb68a6276f8b26/build.gradle#L36-L49). What makes you believe that it's not working?

**Comment by msfjarvis** [comment]
Closed for inactivity.
