### ISSUE TITLE
[Feature Request] Change weather provider on At A Glace widget

### ISSUE THREAD

**Issue by ianmlunaq** [Deletescape-Media/Lawnchair#2626]
I think that being able to change the weather provider app (i.e., AccuWeather, The Weather Channel, etc. instead of weather on the Google app) for the At A Glace widget would be pretty great.

**Comment by Elaborendum** [comment]
I would very much like this feature.

**Comment by Akselmo** [comment]
Also would like this feature. I don't have google app on my phone so I don't get the weather information in smartspace.

I would be interested trying to work on this but it's been long time since I worked with java + i've never touched kotlin (yet). If anyone can point me to the right direction to add weather information to the smart space without google app, i'd love to try to implement it.
