### ISSUE TITLE
(Suggestion) Bring smooth widget opening/closing animations

### ISSUE THREAD

**Issue by kerimgrande** [Deletescape-Media/Lawnchair#2697]
When clicking on a Widget, it just opens like a OneUI 1 / Android 9 app. It'd be a nice thing to have animations that look like in iOS or OneUI 4 when opening a widget.

**Comment by SuperDragonXD** [comment]
**Not sure if this'll work**, but:

1. (Maybe optional) Have Quickswitch (a magisk module, needs root) installed. The module is for the animations when opening.
2. Install Shortcut Maker, then press activities. Find Lawnchair, then click "com.android.launcher3.settings..."
![Screenshot_2022-06-09-13-31-13-13_09e1fc4885c5cbd4072c8ca123d5fff7.jpg](https://user-images.githubusercontent.com/70206496/172771877-c62d4548-8bb7-432f-8f33-c3fdb0bd1a7b.jpg)
3. Press "Try this shortcut". The Launcher3 settings should appear; click "Developer settings"
4. Find "QUICKSTEP_WIDGET_APP_START":
![Screenshot_2022-06-09-13-31-59-19_67d7f8591eff9881972c1169b8bca2d8.jpg](https://user-images.githubusercontent.com/70206496/172772009-971d4e48-5699-404b-9591-e62776066d9b.jpg)
5. Apply, then restart.

If it worked, great! Otherwise, you'll have to wait until the devs provide an app opening/closing setting, and support for widgets.

**Comment by RikKoedoot** [comment]
I believe the animation settings were already working without the toggle for me. But yes, those animations only work when using quickswitch so you'll have to be rooted
