### ISSUE TITLE
Feature Request - Additional options for At A Glance widget.

### ISSUE THREAD

**Issue by kahanzammi** [Deletescape-Media/Lawnchair#2730]
I would like to suggest to add below options to At a glance widget. Hope that will be useful to many Lawnchair users.
 1.  Connected Bluetooth device status 
 2.  Bed time reminders from clock app.

**Comment by gyrorayo** [comment]
Hi, I really love lawnchair, used it for the first time in a custom rom (Havoc 2.9) and missed it since then.
I'd like to ask for a missing feature in At a glance widget, there were messages appearing depending on the time of the day, for example, at morning it'd display "Have you looked outside yet?" or "Have a great day!", and at night it'd display something like "Don't stay up too long" or "What did you do today?"

I mean, it was a nice feature, it made me feel good looking at my phone's screen and having some "wholesome" message to read, hope you can bring it back, I'll try get the same rom on my old g6 Play and take some screenshots.
Thanks in advance

**Comment by kahanzammi** [comment]
> Hi, I really love lawnchair, used it for the first time in a custom rom (Havoc 2.9) and missed it since then. I'd like to ask for a missing feature in At a glance widget, there were messages appearing depending on the time of the day, for example, at morning it'd display "Have you looked outside yet?" or "Have a great day!", and at night it'd display something like "Don't stay up too long" or "What did you do today?"
> 
> I mean, it was a nice feature, it made me feel good looking at my phone's screen and having some "wholesome" message to read, hope you can bring it back, I'll try get the same rom on my old g6 Play and take some screenshots. Thanks in advance

Yes, sometime they made me laugh when it says "Don't stay up too long" .. but it was too late
