### ISSUE TITLE
(Feature Suggestion) Allow Lawnchair 12.1 to be compatible on quickswitch on android 11/10

### ISSUE THREAD

**Issue by notroger7** [Deletescape-Media/Lawnchair#2741]
I have been using lawnchair 12.0 Alpha 5 with quickswitch since its release on my Android 11 device, however, when I updated to 12.1 Alpha 1, it said 'incorrect system configuration' which forced me to revert to the buggy one UI home launcher :( I understand that 12.1 = Android 12L but, 

1. literally 90% of all the launchers I tried only support android 12
2. The stock launcher is pretty trash and I prefer gestures
3. I love the 'app drawer lawnicons' and the 'material 3 radiobutton' features in 12.1

Therefore, I make a suggestion that the devs allow quickswitch on android 11 and 10 for lawnchair 12.1 or make a 12.0 alpha 6 with the new features of 12.1 pls

**Comment by RikKoedoot** [comment]
The developers did not do this because it is quite hard and demoralizing. It would take a while to add which would take away from the rest of development. This is why it didn't happen with the release of 12.1, and I dont think it will happen in the future. A separate app with Android 11 and 10 compatibility would also be a development headache from what I understand.

**Comment by notroger7** [comment]
hmm i see, will launchair 12 final release support android 11? if the final release supports it I don't mind

**Comment by notroger7** [comment]
and will all the legacy features of lawnchair 2 be added to v12? i definitely don't like the adaptive icons ngl

**Comment by RikKoedoot** [comment]
V12 will not receive any more updates. Development is focused on V12.1. Old features might get added but there is no promises on when or which features.
