### ISSUE TITLE
[BUG] Samsung Themed icons not syncing with Lawnchair icons

### ISSUE THREAD

**Issue by roge07** [Deletescape-Media/Lawnchair#2819]
### Describe the bug

I use colour pallette feature in android 12 and I use the icons with a pink colour. However, Lawnchair does not show the icons in that colour; it shows it in the normal app colours

https://user-images.githubusercontent.com/108178571/183586778-df1f0fa0-90c3-4160-b496-da7f741e90e3.mp4

### Steps to reproduce

1. compare lawnchair icons with themed icons on the Samsung phone
2. see the error

### Expected behavior

apps should sync

### Device information

- Device: Samsung Galaxy Note 10 +
- OS: OneUI 4.1.1 Android 12L
- App version 12.1.0 Alpha 4

### Additional context

themed icons also do not update if they change colour

**Comment by SuperDragonXD** [comment]
Isn't really a Lawnchair bug; Samsung only themes the icons in in the Samsung Launcher (similar to Lawnchair theming icons only in Lawnchair).

Unfortunately, there's no way to fix this. You can of course, use Lawnicons in Lawnchair since it could also theme Samsung's icons too (among other apps). Therefore, closing this issue.
