### ISSUE TITLE
Messages in the telegram channel are being automatically deleted

### ISSUE THREAD

**Issue by luigimannoni** [Deletescape-Media/Lawnchair#2827]
Issue entirely unrelated to the launcher itself but a Lawnfeed file has been posted today in the telegram channel.

This has raised some suspects from some of the users, but after the first three messages all the channel seem to delete all comments immediately.

While I do understand that Telegram is a quick way to distribute releases and good for the community it is also the best channel for a bad actor to send to everyone an infected .apk
The fact that the channel is now in slowmode and also deletes all messages are reinforcing the doubts that this is in fact a legit file.

Can someone action immediately on the following points:

- re-enable comments on the Telegram channel
- stop posting files on Telegram and send a link straight to the GitHub release page
- release files to be GPG signed from a trusted developer or CI build

Thanks

**Comment by RikKoedoot** [comment]
Comments are disabled on the channel as people reply there and often don't see the full conversation they've caused.  This is why we disabled it and suggest people to join the help and feedback chat whenever they want to reply.

**Comment by yasanglass** [comment]
there's nothing weird or suspect going on

we decided to lock channel comments since they destroy the flow of conversation in the group and are a pain to deal with, that's it.

Also remember that, since Lawnchair and all our other apps are open source, you can build them yourself and check the hashes against the files uploaded to the telegram channel to check if they're legit.

We prefer uploading files because we think it's easier for everyone to have every apk (Lawnchair, Lawnfeed, Lawnicons) available in one place instead of having them scattered in multiple GitHub repos

**Comment by luigimannoni** [comment]
Thanks for the prompt replies. 

Can the help/feedback channel be circulated around as a sticky message on the news channel and communicate that the news channel is broadcast only?

Sorry for being overly apprehensive and thanks again for the hard work

**Comment by RikKoedoot** [comment]
The group is linked in the channel description
