### ISSUE TITLE
[FEATURE] Month Name

### ISSUE THREAD

**Issue by cyberlog69** [Deletescape-Media/Lawnchair#2830]
### Describe the feature

Date And Time Feature on Lawnchair 12.1 Alpha 4.
![Screenshot_2022-08-11-07-49-23-22_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/52593341/184054301-a891e1c8-3109-4395-b231-85b9295a039d.jpg)

### Why would it be useful to add?

Please Change the Months name From Full name to 3 letter keywords When Time is also enabled in the launcher.

Example: August - Keyword Should be Aug and so on for all the months.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Posting a Picture with Time Disabled.
![Screenshot_2022-08-11-07-52-40-81_67d7f8591eff9881972c1169b8bca2d8](https://user-images.githubusercontent.com/52593341/184054568-4083c469-9b01-467c-a947-7e4a2016b763.jpg)

**Comment by yasanglass** [comment]
This is just everyone's different preference and there is no "best format" for it which means we probably never will just change the current format as we have been using this format since v2 (or even earlier).

The only way to make everyone happy with the format is to let users input the time format they want manually, which I might look into implementing.
