### ISSUE TITLE
[FEATURE] Better or other app opening and closing animations

### ISSUE THREAD

**Issue by BattleChickenHD** [Deletescape-Media/Lawnchair#2856]
### Describe the feature

This function would enable other app opening animations that would bebdifferent than the normal one. Like the ones in OneUI, Pixel Launcher, or older android animations

### Why would it be useful to add?

Better customization, more useful settings

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

In Newest version of nova launcher:
Goto Home screen settings -- search for app-animation -- 'select your app animation'
Finished

### Additional context

Idk what to type here

**Comment by tropicaaal** [comment]
It seems like it's at least *possible* (in some cases) to get better rootless navigation gestures. I've noticed that the Hyperion 2 beta manages to [somewhat recreate the app closing animations](https://twitter.com/prjkt_io/status/1551634957030010881) (where the app transitions into it's icon) using some APIs from launcher3 (specifically [`GestureNavContract`](https://cs.android.com/android/platform/superproject/+/master:packages/apps/Launcher3/src/com/android/launcher3/GestureNavContract.java)). Niagra also mentions this in [their wiki](https://help.niagaralauncher.app/article/7-gesture-navigation) and seems to do it. I've tested both implementations on my OneUI 4 device and they both work *okay*. They're certainly not the same as the stock launcher (they seem to play too early and just fly towards the *general* direction of the icon), but at the very least things don't always scale into the middle of the screen. On AOSP roms this might also look a lot better, since it's the system launcher providing these gestures. Anyways, just some food for thought.

Thanks to Google's botched implementation of gestures and seemingly lack of care for third party launchers, gesture navigation and app animations have been at the forefront of what tends to drive people away from launchers (since what? Android 10?), so it would be nice to see Lawnchair leverage whatever's available if anything better is possible.

**Comment by tropicaaal** [comment]
Update: Apparently the fact that the targeted app animations were playing too early on launchers using these APIs was a bug [supposedly fixed in Android 13](https://issuetracker.google.com/issues/202864574). It'd be ineteresting to see what lawnchair can do with these capabilities.

Edit: It's also been confirmed that OneUI 5 properly implements them - screenshot of Nova Launcher, which has a rootless GestureNavContract implementation (credit: Arkyne#9953)

https://cdn.discordapp.com/attachments/469227559851261953/1023690256945528962/lv_0_20220922142728.mp4

**Comment by getlocaladmin** [comment]
Can we get this implemented please??

**Comment by JagritThukral** [comment]
Add this please!

**Comment by LooneyH** [comment]
Definitely think this is worthwhile as an addition. It's a small touch but I have always loved Lawnchair for its slick use of animations, and I know other launchers such as Nova Launcher 8 (in its beta currently) have at the very least emulated this effect well.
