### ISSUE TITLE
[FEATURE] Compatible Live wallpaper for lite android

### ISSUE THREAD

**Issue by Fauzi1237** [Deletescape-Media/Lawnchair#2864]
### Describe the feature

Built in Live wallpaper for lite android

### Why would it be useful to add?

Because of android lite limitation, it can't use live wallpaper. 
My device is Realme C11 (2021) {RMX3231} 32-bit OS.
None of any live wallpaper app work for me.
Thanks :)

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

For examples... I.. I think it's like when you go to home screens, hold blank area, then click on wallpapers, then click on it and system will ask "complete action with :",then there will be an option "lawnchair live wallpaper".
Something like that and sorry for bad explanation.. 

### Additional context

Maybe an options to pick wallpaper/live wallpaper trough lawnchairs home screen settings
![IMG_20220822_201811](https://user-images.githubusercontent.com/95536104/185931063-10c4f501-4d91-4b9e-aeac-782e8ec47cb9.jpg)

**Comment by SuperDragonXD** [comment]
This issue happens because Android lite (Go)/your OEM removed the API to allow live wallpapers. Lawnchair or any other third party app can't change this in any way (unless if you change some device config using root). Also, we do not currently plan on having a custom "wallpaper and style" menu. Closing this issue.
