### ISSUE TITLE
[FEATURE] Change Folder Icons

### ISSUE THREAD

**Issue by butjer** [Deletescape-Media/Lawnchair#2940]
### Describe the feature

Change the icon of folders

### Why would it be useful to add?

Must have for nice desktop pages

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

![Screenshot_20220913-103941_Lawnchair](https://user-images.githubusercontent.com/4136780/189854491-60c8d5cb-9d03-499c-b6bf-047b73196e57.png)

**Comment by wiraki** [comment]
Not sure if that is what is meant because the screenshot just shows the contents of a folder, but I think being able to set a specific icon to be the "cover" of a folder is crucial!

**Comment by aRav3n** [comment]
Yes please! Lawnchair 12 is great but this is definitely my most missed feature from Lawnchair 2!

**Comment by cynber** [comment]
This is one of the most important features that's missing for me. Otherwise, it's much harder to differentiate between folders. I added some better screenshots below.

It could function similar to the icon selection that pops up when an app is being edited. 
![Screenshot_20230430-052638](https://user-images.githubusercontent.com/26402139/235353410-533feb52-cbcd-4303-9731-8d5c3f1427f0.png)


A quick before and after is here:
![' Screenshot_20230430-052830](https://user-images.githubusercontent.com/26402139/235353231-49b7d711-7f01-451f-95f6-a62edab504f8.png)
