### ISSUE TITLE
[BUG] Lawnchair 12 doesn't force icon shape like in Lawnchair 9

### ISSUE THREAD

**Issue by midiidev** [Deletescape-Media/Lawnchair#2996]
### Describe the bug

Lawnchair 12 doesn't force the selected icon shape like it does in Lawnchair 9.

### Steps to reproduce

1. Select an icon shape that is not the same as your system's
2. Go back to the home screen, and you'll see that system icons don't conform to the selected icon shape.

### Expected behavior

Selecting an icon shape functions the same in Lawnchair 12 as it did in Lawnchair 9 by making system icons (icons not themed with Lawnicons) change to the shape selected.

### Screenshots

Lawnchair 9 (all icons are round, as expected)
![Screenshot_20221002-094433_Lawnchair](https://user-images.githubusercontent.com/101067949/193475832-633393ea-3942-4546-96a7-2630757afcbf.jpg)

Lawnchair 12 (icons don't use the selected icon shape and instead use the system one)
![Screenshot_20221002-094544_Lawnchair](https://user-images.githubusercontent.com/101067949/193475889-6ff45d12-b0e0-4557-828d-1cf2889e31f3.jpg)

### Device information

- Device: Samsung Galaxy Note20
- OS: OneUI 4.1 / Android 12
- App version: 12.1 Alpha 4

**Comment by SuperDragonXD** [comment]
Not really a bug. Lawnchair 12.1 doesn't mask/crop the icons to match the icon pack since that's isn't a feature for now.

You can try using adaptive icons (which adds a colored container to the icon), change the icon shape in Hpme Settings > General > Icon Shape > Choose "Circle" or use another icon pack.

Also closing this issue since (read first sentence). Feel free to create a new feature request regarding this.
