### ISSUE TITLE
[FEATURE] At a Glance Text Align 

### ISSUE THREAD

**Issue by passeee** [Deletescape-Media/Lawnchair#3015]
### Describe the feature

Ability to change At a Glance Text Alignment to center (or right)

### Why would it be useful to add?

More space usage 

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![Screenshot_20221011-000448](https://user-images.githubusercontent.com/96446439/194959320-8dac40ad-2bd6-4159-a385-55727952defe.png)

### Additional context

Idk if it existed in V2

**Comment by Username1-a** [comment]
Also, would be neat to have option to change vertical alignment, so that it could've been centered. 
Right now, At a Glance text is higher within the widget boundaries, so it looks bad with other widgets by the side of At a Glance widget, because they have different height.
Example:
![Screenshot_20221013-045456_Lawnchair](https://user-images.githubusercontent.com/47947180/195481188-65dc7e39-b080-4257-ad18-29b49661e541.png)
