### ISSUE TITLE
Custom app drawer layout

### ISSUE THREAD

**Issue by squabbi** [Deletescape-Media/Lawnchair#362]
Could custom arranging apps in the app drawer be possibly considered in a future release? Similar to the stock LG and Samsung launchers (I'm sure there are other launchers that can do something similar to this too).

Thanks for the great work so far! 👍

**Comment by Williwood** [comment]
For the beginning I would like to see to change the order of the apps. I would like to sort them after most used apps.

**Comment by nrk** [comment]
That would be **awesome**. The only reason I'm still sticking with a custom Xperia Home build even on my OnePlus 3T is exactly because of the ability to arrange icons in folders and multiple pages in the app drawer simply by dragging their icons around just like you'd do in the home screen. AFAIK Nova Launcher is the only third party launcher with something similar, but it's implemented in a ridiculous way.

**Comment by guest4711** [comment]
See also #544

**Comment by guest4711** [comment]
See also #671
