### ISSUE TITLE
[BUG] Folders not opening with upgrade to android 14

### ISSUE THREAD

**Issue by traal007** [Deletescape-Media/Lawnchair#3647]
### Describe the bug

The folders are not opening as appropriate when clicking on the icon. Appears to be an error with the upgrade to Android 14

### Expected behavior

Expect the apps to appear as per normal 

### Device information

Pixel 7
Android 14

**Comment by eggsgent** [comment]
Does opening fail every time or only sometimes for you?

On my device, Samsung Galaxy S23 Android 1, Lawnchair 12.1 Alpha 4, App folders on home screen fail to open sometimes (same app within the folder opens instead). At the same time, navigation to app drawer fails.

**Comment by Mystic-duck** [comment]
Hello, I waited till yesterday to install the Android 14 UP1A.231105.003 update, hoping for less bugs, 

but I have the same problem rn on my pixel 6a, folder are not showing when I open them, it still opens tho even if invisible, since I can hit the app in it then.

It does the same with launcher built in settings (long trap on the background)

 When I restart the launcher it temporarily fixes the problem
