### ISSUE TITLE
[BUG] sometimes i can't open app drawer

### ISSUE THREAD

**Issue by Fr3uds** [Deletescape-Media/Lawnchair#3934]
### Describe the bug

sometime i can't open app drawer 
[2024-01-02_19.01.zip](https://github.com/LawnchairLauncher/lawnchair/files/13814475/2024-01-02_19.01.zip)

https://github.com/LawnchairLauncher/lawnchair/assets/52089042/dd7d3b81-36cc-4286-93d7-764c5303815c

### Steps to reproduce

it's totaly random, i don't know how to reproduce

### Expected behavior

open the app drawer

### Device information

- Device: [e.g. Google Pixel 6]
- OS: [e.g. stock ROM Android version 12.0]
- App version: [e.g. 12.1.0 Alpha 4]
Poco F5 with evox, last beta build

**Comment by guifarias31** [comment]
I am also having this issue since last Samsung update.

Device: Samsung Galaxy S23
OS: Android 14 / One UI 6.0
App version: 12.1.0 Alpha 4

**Comment by RunasSudo** [comment]
I've observed this issue on my device on both Lawnchair 12 and the current 14-dev build. Locking and unlocking the screen resolves the issue temporarily.

Device: Pixel 8
OS: Android 14
App version: 14-dev build #299, commit 28412aa

**Comment by Jim-Bar** [comment]
I have this exact same problem, since a few months (I think since the upgrade to Android 14).

It turns out the drawer actually opens but is invisible. When clicking on an empty spot on the screen, it opens the app that would normally be visible at that spot with the drawer open. When it occurs, by playing a bit with the navigation and recent apps, it can happen in reverse: the drawer is visible whereas the home screen should be visible. Then tapping on an app instead triggers what would occurs when taping on the home screen at the same spot: nothing if there is nothing, open an app if there is a shortcut, etc…

Device: Pixel 4a 5G
OS: Android 14
App version: 2.0-2589 (reported by Google Play Store)

**Comment by Fr3uds** [comment]
@MrSluffy why is tagged outdated sir?

**Comment by Sxderp** [comment]
I'm having the same problem on A14. I don't think the outdated tag is appropriate. I've seen the same as @Jim-Bar in that the drawer "opens" but is invisible. I don't think I've seen the "reverse" as they describe it.

I've tried with Lawnchair 12 and Lawnchair 14. But since Jim-Bar is using version 2, I'm guessing this is a bit of code that's roughly the same across the versions.

I figured out a way to reproduce on my phone.

1. Place the clock app on your Home Screen (for convenience really).
2. Press the home button so that you're at the "base" Home Screen.
3. Open the clock and set an alarm for one or two minutes from now.
4. Press the home button to go back to the Home Screen.
5. Turn the display off.
6. Wait for the alarm.
7. Dismiss the alarm.
8. At this point I'm on the Lock Screen. I don't have a pin so I just swipe up which brings me to the Home Screen.
9. I swipe up again to bring up the drawer. The drawer is invisible, but if I press on the middle of it I can open apps.

**Comment by MrSluffy** [comment]
Use latest lawnchair 14

**Comment by Sxderp** [comment]
Please reopen. The issue is present in Lawnchair 14 Beta 2. 

The reproduction I posted earlier is still valid.

**Comment by c4tz** [comment]
Still present in v14 Beta 3 (on Android 14). Also, when you have grouped apps on the homescreen, the groups will open invisible, too.

I can only "work around" (which still bugs me when I just quickly want to check something) this by locking and unlocking my phone.

I really like Lawnchair, but this seems like a major bug to me 😕 Please reopen.

**Comment by sorin-silaghi** [comment]
I have the same issue on Lawnchair 2.0-2589 om my Galaxy s24 with android 14. The app drawer seems to be invisible. Also folders on the home screen don't work, tapping on them just opens one of the apps instead of showing the contents.

**Comment by pgalmon** [comment]
Not sure if this helps but when I turn off battery saver mode it fixes it temporarily. Also when I switch the hrtz of the screen it seems to effect it and my app drawer. Not sure if any of this makes sense lol

**Comment by to01** [comment]
Can confirm the issue still occurs on version 14.Beta.3

Specs if useful:
Samsung A54 5G

**Comment by FayKn** [comment]
Same issue on 14.Dev.(d7e3f32)

On a 
Poco F6
HyperOS 2.0.105.0 (Android 15)

**Comment by Nirav186** [comment]
I am still getting this issue

**Comment by larswars83** [comment]
I have This issue also!
