### ISSUE TITLE
Quick slider and Notification colour

### ISSUE THREAD

**Issue by thecipherman** [Deletescape-Media/Lawnchair#398]
Give option to on/off quick slider in app drawer because there is search option so no meed quick slider. And one bug I found that on Google now page notification pannel remain white while page os also white but on app drawer it goes dark which is good.

**Comment by fonix232** [comment]
1. We are not going to clutter the settings with something that will barely be used by anyone. If you don't want the quick slider, just ignore it.

2. We cannot affect the Google Now page in any way. Lawnchair is simply invoking the native library, which takes over pretty much everything, including the animation (that's why we can't do much about the jaggedness of the animation).
