### ISSUE TITLE
[BUG] android 14, no option to allow restricted setting

### ISSUE THREAD

**Issue by spice42** [Deletescape-Media/Lawnchair#4125]
### Describe the bug

no option to allow restricted setting. making gestures and notification dots unusable

### Steps to reproduce

1. Go to - settings, change gestures, double tap to sleep
2. Click on - kebab 3 dot menu, no option to allow restrictive settings 
3. See error - Restricted setting

### Expected behavior

expect to change the accessibility setting however its greyed out

### Screenshots

![Screenshot_20240313-141238_Lawnchair](https://github.com/LawnchairLauncher/lawnchair/assets/113236440/56e73207-cf61-412c-96b3-3c0a4cb88f0d)

![Screenshot_20240313-141425_Trebuchet](https://github.com/LawnchairLauncher/lawnchair/assets/113236440/522c86c0-e1b8-4439-974c-d47682d362c6)

### Device information

- Device: Google Pixel 6
- OS: LineageOS 21.0 android 14
- App version:  12.1.0 Alpha 4

**Comment by spice42** [comment]
sorry, found it, here

![Screenshot_20240313-144109_Trebuchet](https://github.com/LawnchairLauncher/lawnchair/assets/113236440/1829a185-5d3b-471f-9ace-3c8a724f8be0)

**Comment by PowerUser64** [comment]
I ran into this too. Turns out you have to enable "Allow restricted settings" in the upper-right corner menu of Lawnchair's app info page in settings.

Here's an image from [an article on techwiser.com](https://techwiser.com/how-to-bypass-restricted-accessibility-settings-on-android-13-14/) that shows where to find it:

![image](https://github.com/LawnchairLauncher/lawnchair/assets/24578572/41ef26db-c15b-4c60-a5eb-aaa8c70aab05)

Hopefully this helps anyone else that encounters this.

**Comment by breversa** [comment]
@PowerUser64 Thank you!! I was getting crazy about this!
