### ISSUE TITLE
Hidden Apps showing in search results 

### ISSUE THREAD

**Issue by harsh251004** [Deletescape-Media/Lawnchair#4156]
### Describe the bug

Hidden apps are visible in app drawer search results.
Eg -
I had hidden Among us. It wasn't visible in the home screen or app drawer but it was visible when I typed the letter "a" in the app drawer search.

### Steps to reproduce

1. Hide any app
2. Search for the app in the app drawer 
3. See it shows the app

### Expected behavior

It shouldn't be displaying hidden apps in app drawer search results. What's the point of it being hidden if it can be accessed via the app drawer search.

### Screenshots

![Screenshot_20240328-120949](https://github.com/LawnchairLauncher/lawnchair/assets/146340558/8fc3e965-44aa-4cfc-9c9c-0a9ea2778b9b)
![Screenshot_20240328-120940](https://github.com/LawnchairLauncher/lawnchair/assets/146340558/b7a6b925-da58-4509-943a-e3b067d2369c)
![Screenshot_20240328-120923](https://github.com/LawnchairLauncher/lawnchair/assets/146340558/29792ef9-0a04-4db9-b3f0-4bc4bc31be19)

### Device information

- Device: [Motorola Edge 30]
- OS:  [ MYUX (close to stock) ROM Android version 13.0]
- App version: [12.1.0 Alpha 4]

**Comment by nathangur** [comment]
Actually I like being able to hide apps and search them in the app drawer. I think a toggle would be best but having it on by default is good. And it's also how other launchers, even official ones like Samsungs os allow for searching of hidden apps. I like it since I can hide important things such as banking apps to not be viewed by just anyone.

**Comment by MrSluffy** [comment]
there's a toggle in settings "Hide in search result"
