### ISSUE TITLE
[BUG] Google Feed Not Working

### ISSUE THREAD

**Issue by Lindsor** [Deletescape-Media/Lawnchair#4201]
### Describe the bug

I upgraded from Lawnchair 2 and uninstalled the old Lawnchair as well as Lawnfeed. I've installed Lawnfeed 3 and Lawnchair 14 and enabled Google feed. However when I scroll on the homepage to the leftmost I no longer land on Google feed. Nothing happens

### Steps to reproduce

1. Go to homescreen
2. Scroll to left
3. Notice nothing happens

### Expected behavior

I expect the google feed to show up on the leftmost homescreen. 

### Device information

- Device: Samsung Galaxy S23 Ultra
- OS: Android 14 One UI 6.1
- App version: 14 Beta 2

**Comment by thinkgadgetsme** [comment]
Google feed worked for sometime, however, it stopped working after a while.

**Comment by kymerea** [comment]
I've also noticed this, but I didn't come from lawnchair 2 or 3. I came from the 14 Dev builds. It worked fine there but now it doesn't work at all in the beta builds

**Comment by ajneil-gh** [comment]
Same issue, fresh install of beta 2 on Android 14 pixel 7

**Comment by Hugo-Ottati** [comment]
Same problem here! I just installed the new lawnchair 14 Beta 2 and I can't open the feed!

**Comment by Aljosha89** [comment]
+1 here

**Comment by vndre** [comment]
Same here. Pixel 8. Lawnfeed 3 worked for the very first minutes, then nothing. Tried uninstalling and reinstalling both with no success.

**Comment by peppefender** [comment]
Same issue here, with Lawnchair 14 fresh installed on Pixel 5 with latest Android 14 stock update.

**Comment by MrSluffy** [comment]
Try force stopping google app if still persist use this alternative : https://github.com/amirzaidi/AIDLBridge

**Comment by vndre** [comment]
> Try force stopping google app if still persist use this alternative : https://github.com/amirzaidi/AIDLBridge

This is by far not a solution to this bugs multiple users are reporting. Even if force closing Google App works (which it didn't in my case) are we expected to keep doing it everytime Lawnfeed stops working?

**Comment by Bennett-69** [comment]
FYI, especially for those of us upgrading from dev builds:

The Google app (which generates the Feed) apparently only accepts requests from Debug and System apps. Hence, when Lawnchair 14 moved from a debug app into beta, it lost default access to the Google Feed.

One easy way I stumbled upon to fix this (at least with root access) is to install QuickSwitch. As part of its initial setup, it "systemizes" the Lawnchair APK, so it subsequently regains Google Feed access as a side effect.

You can tell if Lawnchair has been turned into a System app, when looking at its App Details: instead of an "Uninstall" option, it will change to "Disable" (as System apps normally can't be uninstalled).

**Comment by Zorachus** [comment]
Installed Lawnchair14 beta 2 on my Pixel 8 Pro, and Lawnfeed3 and the Google Feed worked briefly, then just disappeared stopped working.

**Comment by LarveyOfficial** [comment]
Seems the only option is to either have a rooted device, or use the nightly build. Beta 2 doesn't seem to work no matter what I do on a Stock Pixel 8 Pro. 

So far nightly has been alright, but you can tell it's a debug build as it's very buggy and laggy sometimes.

**Comment by ramonskie** [comment]
Is there already some progress on this? I switched from debug to beta. But if not then i will switch to the highly(debug) version again

**Comment by coldhanded** [comment]
Can confirm this issue still exists in Beta 2. Any updates on a fix aside from using nightly builds for non-root users?

**Comment by kymerea** [comment]
Someone should really just pin this everywhere on the github and the discord

https://discord.com/channels/803299970169700402/803304748920078337/1239093510209146952

"Last of all, some users are experiencing issues with getting lawnfeed to work, a workaround could be to force stop the google app or rebooting your phone, if that does not work, install aidlbridge, available [here.](https://github.com/amirzaidi/AIDLBridge/releases)"

**Comment by srprtl** [comment]
Solved problem next way: Option double tap on home screen,choose open app, choose google app, vuala

**Comment by 0-BlackSpectrum-0** [comment]
Same issue here in beta 3

**Comment by 0-BlackSpectrum-0** [comment]
> Someone should really just pin this everywhere on the github and the discord
> 
> https://discord.com/channels/803299970169700402/803304748920078337/1239093510209146952
> 
> "Last of all, some users are experiencing issues with getting lawnfeed to work, a workaround could be to force stop the google app or rebooting your phone, if that does not work, install aidlbridge, available [here.](https://github.com/amirzaidi/AIDLBridge/releases)"

This is also not working 🥲

**Comment by matthewmgraf** [comment]
Solved this issue (using 14 beta 3). For me, the issue was that I had selected the "Feed Provider" as Google in Lawnchair > Home Settings > Home screen. I did a full uninstall/reinstall of both Lawnchair and Lawnfeed, tested the feed functionality and it worked (note, I did not change the feed provider, it was unselected). Just had to redo all my settings after. I also took backups of my settings before and after, and through toggling between backups I could confirm that this is a configuration issue with the feed in Lawnchair.

I guess the solution to this is to 1) have the feed toggle reset the feed configurations and 2) allow editing of backups so I can change those settings without having to start everything from scratch. I'm sure there is a way to adjust those backups, but they are not in a format that I can edit from a text editor. If someone has an idea on how I can edit those files, please let me know. It would also be helpful to have an advanced configuration editor where I can edit the backups from the app itself.

**Comment by zwamdurkel** [comment]
> Solved this issue (using 14 beta 3). For me, the issue was that I had selected the "Feed Provider" as Google in Lawnchair > Home Settings > Home screen. I did a full uninstall/reinstall of both Lawnchair and Lawnfeed, tested the feed functionality and it worked (note, I did not change the feed provider, it was unselected). Just had to redo all my settings after. I also took backups of my settings before and after, and through toggling between backups I could confirm that this is a configuration issue with the feed in Lawnchair.

I'm having this same issue. After selecting Google as the "Feed Provider" my feed broke. Resetting the app fixes it. There is no way to deselect google as the feed provider without deleting your entire configuration!!

**Comment by Shesh1994** [comment]
Hey guys,
I'm landing here with the fix which I almost figured out after one year..
After searching a lot to try the fix..
You can download The Rootless Pixel Bridge, it works 💋
https://www.apkmirror.com/apk/amirzaidi/rootless-pixel-bridge/rootless-pixel-bridge-v3-release/rootless-pixel-bridge-v3-android-apk-download/

**Comment by zwamdurkel** [comment]
> Hey guys, I'm landing here with the fix which I almost figured out after one year.. After searching a lot to try the fix.. You can download The Rootless Pixel Bridge, it works 💋 https://www.apkmirror.com/apk/amirzaidi/rootless-pixel-bridge/rootless-pixel-bridge-v3-release/rootless-pixel-bridge-v3-android-apk-download/

Don't know how I feel about abandoned software as a "fix" when I also don't really know why this is a fix.
