### ISSUE TITLE
[BUG] Folders sometimes not opening on Android 14 (older issue, still present on Lawnchair 14 beta 2)

### ISSUE THREAD

**Issue by eggsgent** [Deletescape-Media/Lawnchair#4256]
### Describe the bug

Folders sometimes not opening on Android 14 (old issue, still present on Lawnchair 14 beta 2).

See #3647, same issue still on an imported setup from previous Lawnchair release, 12.1.0 Alpha 4.

### Steps to reproduce

1. Have some folders on the homescreen.
2. Try opening them.

Actual result: From time to time the folder will not open, instead, sometimes an app inside the folder, which is positioned where the folder press happens, opens instead.

### Expected behavior

Folders to always open

### Device information

- Device: Samsung S21
- OS: Android 14
- App version: Lawnchair 14 beta 2

**Comment by MrSluffy** [comment]
Did you disable system animation?

**Comment by eggsgent** [comment]
No, everything set to x1 in dev settings, reducing animations not enabled in Accessibility

**Comment by eggsgent** [comment]
Possibly same bug with another symptom:

After unlocking the phone from lockscreen, user cannot access the app drawer, swipe gesture does not result in app drawer being pulled up.

**Comment by nowster** [comment]
This seems to be a problem introduced by Android 14's December feature drop update (QPR1).

The launcher does not appear to get control of the screen and does not redraw itself at all. Taps do work and you can launch apps that are immediately visible on the home screen (ie. not in folders or the drawer). If you can guess what the state of the screen is you can still do things.

Swiping between screens has no visible effect but does happen. You can swipe to the Feed and that shows correctly, but the home screen does not redraw when you swipe back.

This problem is not unique to Lawnchair: Nova Launcher was also affected. As I no longer use that I have no idea if they found a workaround.

The workaround is to lock the phone and unlock it again.

**Comment by MrSluffy** [comment]
Can you try and check latest nightly if still persists reopen this issue
