### ISSUE TITLE
App Close animation is not smooth[BUG] 

### ISSUE THREAD

**Issue by srini-vasan-r10** [Deletescape-Media/Lawnchair#4514]
### Describe the bug

Whenever I open an app from home screen and try to close it native pixel launcher will make it as a smooth fade in animation to the icon from the screen.. but it is bit laggy in the version Launcher 14 Beta 2
![gif-20240626-200917](https://github.com/LawnchairLauncher/lawnchair/assets/114680730/db3ea41e-2ce3-455b-ba43-22d077aa02f2)

### Steps to reproduce

1. Unlock the phone
2. Click on any app on home screen.
3. Try to close..
4. It is laggy on closing animation.

### Expected behavior

A smooth flow to the app icon is expected.

### Device information

- Device: Motorola G84 5G
- OS: [e.g. stock ROM Android version 14.0]
- App version: Lawnchair 14 Beta 2

**Comment by zty012** [comment]
if you have root, you can use this module:

https://github.com/skittles9823/QuickSwitch#installation

**Comment by gordongw** [comment]
What kind of comment is that? If you have root your phone's security is shot. This should be fixed without root, and if it is not possible, well then Lawnchair has reached the end of the road.

**Comment by 0xAbdiiii** [comment]
Until Android 9 Pie, Android's stacked card recent apps interface remained largely unchanged since it was first introduced in Android 5.0 Lollipop. With the introduction of gesture navigation in Android Pie, Google revamped the recent apps overview screen. The new interface features large overview cards arranged horizontally, but that isn't the biggest change to the recent apps interface. Since the code for recent apps is now integrated into the stock launcher, you can now seamlessly transition from your recent apps overview to your launcher's app drawer. As AndroidCentral's Ara Wagoner explains, this puts third-party launchers at a disadvantage because only the pre-installed system launcher can integrate with the recent apps UI. On the other hand, if you have root access, Android Pie's changes to the recent apps overview actually opens up a whole new avenue of customization.

**Comment by iamtheabdi** [comment]
Just a quick Google search and you wouldn't have had any need to be rude in your last comment.

**Comment by 0xAbdiiii** [comment]
Have a quick read:

https://www.xda-developers.com/android-pie-recent-apps-customization/

**Comment by MrSluffy** [comment]
Can you try and check latest nightly or quickswitch if still persists reopen this issue
