### ISSUE TITLE
[BUG] Color Style not working on One UI 

### ISSUE THREAD

**Issue by ujwal246** [Deletescape-Media/Lawnchair#4543]
### Describe the bug

Newly added feature in debug build "Color Style" is not showing on One UI.
Dev please take a look.

### Steps to reproduce

Steps to reproduce the behavior
Go to "General" > "Color Style".

### Expected behavior

Should work as intended.

### Screenshots

![IMG_20240705_123118_055](https://github.com/LawnchairLauncher/lawnchair/assets/117264003/98c9ce96-d440-4c81-9808-612aa201105d)
![IMG_20240705_142518_640](https://github.com/LawnchairLauncher/lawnchair/assets/117264003/44a8b79a-671d-4460-9bb8-b990429afe4b)

* Screenshots : "Color Style" showing on some users phones. 👆

![Screenshot_20240705_143515_Lawnchair (Debug)](https://github.com/LawnchairLauncher/lawnchair/assets/117264003/08114aea-d02e-47c0-8734-8fcd7e4bb6c2)
"Color Style" absent in my case. 👆

### Device information

- Device: Samsung F22
- OS: One UI 5.1 Android 13 
- App version: build # 1059

**Comment by SuperDragonXD** [comment]
"Color Style" is absent when you are on Android 12+ and are using the `System` accent color. This is due to the fact that the system color scheme picker already has those options in a more visual format:

![Screenshot_20220901_135354.jpeg](https://github.com/LawnchairLauncher/lawnchair/assets/70206496/664cdeab-d001-4b91-a278-06f8406ad5ed)

If you wish to change your color style, simply change it via your system settings, or change Lawnchair's Accent color to use either Wallpaper, or the presets/custom colors.
