### ISSUE TITLE
[BUG] Can't read notifications, even though I have allowed it in the settings 

### ISSUE THREAD

**Issue by Yan75** [Deletescape-Media/Lawnchair#4563]
### Describe the bug

I can't turn on the notification dots, and it's playing on At a glance, The application asks to approve the notification reading request, even though I have allowed it in the settings 

### Steps to reproduce

1. Go to 'Home Settings'
2. Click on 'General'
3. Scroll down to 'Notification Dots'

### Expected behavior

Hopefully it will be fixed quickly 

### Screenshots

https://github.com/user-attachments/assets/6897d829-5cc7-43c3-9495-6c2c2e6820ef

### Device information

- Device: [IQOO Z7 5G (SD782G) ]
- OS: [FUNTOUCH OS 14 ANDROID 14]
- App version: [Lawnchair.Debug.14-dev.Nightly-CI_1081-958c25d]

**Comment by SuperDragonXD** [comment]
Hey there,

Could you try to enable Notification Dots via your stock launcher settings, or within the notification settings itself? The team doesn't have a device with Funtouch OS, so we can't really give precise steps.

**Comment by breversa** [comment]
Same here on a Fairphone 5 running /e/OS 2.2.

The default launcher (Bliss Launcher) has access to apps notifications, but I cannot give the same access to Lawnchair due to "security concerns". See below :

![Screenshot_20240821-110454_Lawnchair](https://github.com/user-attachments/assets/21c34f4a-4537-40f8-a518-b77cf1aace2c)

![Screenshot_20240821-110408_Paramètres](https://github.com/user-attachments/assets/a375f9ce-3452-405c-957f-754d69e535a1)

![Screenshot_20240821-110414_Paramètres](https://github.com/user-attachments/assets/69c58ffa-07db-4f92-8d32-67a70dbdf5dd)

**Comment by breversa** [comment]
Solution here: https://github.com/LawnchairLauncher/lawnchair/issues/4125#issuecomment-2041406621

**Comment by MrSluffy** [comment]
Please allow restricted as @breversa mentioned
