### ISSUE TITLE
[BUG] [Nightly build] issues in Settings

### ISSUE THREAD

**Issue by Stephan-P** [Deletescape-Media/Lawnchair#4574]
### Describe the bug

Lawnchair 14.Dev. (# 1085) on Google Pixel 7a with GrapheneOS (latest: 2024071200)

In Settings:
The menu option Dock is not translated. String is not available in Crowdin

In Settings - Dock:
The title Dock is not translated. The string is not available in Crowdin

In Settings - anywhere:
The button Back in the top left does not function. One can only swipe right-to-left from the screen edge.

In Settings - anywhere:
Scrolling up/down is not fluent

### Steps to reproduce

Open Lawnchair settings

### Expected behavior

See description above

### Device information

- Device: Google Pixel 7a
- OS: GrapheneOS 2024071200
- App version: 14.Dev. (# 1085)

**Comment by SuperDragonXD** [comment]
Hey there,

For the crowdin string issues, could you tell me your device language? As a note, I'm not really sure what’s going on with missing strings, so can't fully help in there for now.

For the back button issue, could you tell me your Android version (include QPR version if possible)? Not really sure what Android version GrapheneOS `2024071200` uses.

The laggy/janky scrolling in Settings is intentional due to the builds being `debug`-able (to disuade the average user from using unstable builds).

**Comment by Stephan-P** [comment]
My device language is Dutch.
In Crowdin-Lawchair-Dutch there are no source strings "Dock". So I would assume this to be a hard coded text with no translation reference.

GrapheneOS is based upon the latest from AOSP, that is Android 14 QPR3 (https://grapheneos.org/releases)

Ah, debug information. That makes sense. Thank you.

**Comment by Stephan-P** [comment]
> In Settings - anywhere: The button Back in the top left does not function.

This issue appears to have been resolved in today's build
