### ISSUE TITLE
[FEATURE] Android 15's Private Space support

### ISSUE THREAD

**Issue by justbearcause** [Deletescape-Media/Lawnchair#4745]
### Describe the feature

Android 15 introduced a new feature called Private Space.
More info can be found in release notes: https://android-developers.googleblog.com/2024/05/the-second-beta-of-android-15.html

### Why would it be useful to add?

This feature allows to keep sensitive apps and their data separate from all others. It also allows to have two instances of the same app installed simultaneously.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

![image3](https://github.com/user-attachments/assets/2570a996-ce3c-4924-9e3e-b15af95ceb7f)

**Comment by SuperDragonXD** [comment]
This will probably be implemented once:
* Android 15 source code of Launcher3 is publicly available 
* We merge Launcher3 source to Lawnchair

**Comment by pdf** [comment]
Relevant:

https://issuetracker.google.com/issues/352276244

**Comment by brainchild0** [comment]
I have failed to access the feature, reported as merged into the branch tagged nightly, from running the nightly build.

Since use of the feature is virgin territory, I may be doing so improperly. However, I have followed the instructions from the post and other sources as well as possible, after enabling the overall feature in the system configuration.

How can I ensure that I have installed a version that includes the feature?

The application details show "version 15.Dev.(\#1946)", based on a download from nightly builds on 18 Jan 2025.


---


*Update:* After some fiddling with application permissions, the feature eventually appeared, displayed in the app drawer, as documented.

Perhaps someone who understands the design could comment on the relationship between the appearance of the feature and the application permissions, in particular, which permissions are necessary.


----

*Further update:* See [later comment](https://github.com/LawnchairLauncher/lawnchair/issues/4745#issuecomment-2601366225).

**Comment by MrSluffy** [comment]
Make sure you using Android 15 and have enable Private Space Device Settings configuration

**Comment by brainchild0** [comment]
@MrSluffy: I have already done both as you suggest. Presentation of the feature appears to be sensitive to the permissions of the application.

**Comment by MrSluffy** [comment]
what permission? you unable to private space to work? make sure disable Disable Hide Private space from settings you can check this https://issuetracker.google.com/issues/352276244

**Comment by brainchild0** [comment]
@MrSluffy: Some of the systems permissions for the application, Lawnchair, appeared to account for the difference.

**Comment by thavan** [comment]
I observed in the new beta version, private space unlock button is not showing first time in the launcher if it is not unlocked already. Once you unlock it from Android settings it shows the button in launcher.

**Comment by brainchild0** [comment]
I am wondering whether not having the application set as the system launcher, but rather its running simply as a normal user applications, might account for the feature not appearing to me originally.

**Comment by pdf** [comment]
If it's not the default launcher, no profiles are available (work or private), however I also noticed that when set as default, the private space didn't show up until I explicity restarted Lawnchair.

**Comment by brainchild0** [comment]
I have now confirmed that assigning the default launcher as a different application causes the functionality to disappear, for Private Spaces, within the application, and that assigning the application as the default launcher, and also restarting the application, are both required to restore such functionality in the application.
