### ISSUE TITLE
[BUG] crash on tablet (MiPad 4 Plus Mokee 11)

### ISSUE THREAD

**Issue by chuwza** [Deletescape-Media/Lawnchair#4785]
### Describe the bug

Lawnchair 14.beta 3 can't launch on MiPad 4 Plus, but Lawnchair Nightly can launch 

### Steps to reproduce

1. Install the 14.beta 3
2. go to home
3. crash

### Expected behavior

Can open Lawnchair normally

### Device information

- Device: [MiPad 4 Plus]
- OS: [Mokee 11.0]
- App version: [14.beta 3]

### Additional context

[Xiaomi Pad 4 Plus 14.beta3 crash log.txt](https://github.com/user-attachments/files/16938541/Xiaomi.Pad.4.Plus.14.beta3.crash.log.txt)

**Comment by NekoMimiOfficial** [comment]
If it works fine on the nightly build then the issue is fixed, you'll just have to wait for the next beta release

**Comment by chuwza** [comment]
> If it works fine on the nightly build then the issue is fixed, you'll just have to wait for the next beta release

OK, so when is the next update? Will it take a couple months? Or a couple weeks?

**Comment by NekoMimiOfficial** [comment]
It can take months, beta 3 has just been released a couple weeks ago, but they are porting the A15 version of launcher3 

As I mentioned, this issue is already solved, if you don't like using nightly you can use goooler's fork instead but it has a different signature so you'll need to uninstall beta 3 then install goooler's fork, or you can just wait for either beta 4 or lawnchair 15

**Comment by chuwza** [comment]
> It can take months, beta 3 has just been released a couple weeks ago, but they are porting the A15 version of launcher3
> 
> As I mentioned, this issue is already solved, if you don't like using nightly you can use goooler's fork instead but it has a different signature so you'll need to uninstall beta 3 then install goooler's fork, or you can just wait for either beta 4 or lawnchair 15

OK, thank you very much !
