### ISSUE TITLE
Lawnchair requests

### ISSUE THREAD

**Issue by Dondrejohnson5** [Deletescape-Media/Lawnchair#50]
- Make Calendar and Clock app dynamic (today is June 27, but the icon still says 26)

- Try these Google Pixel icons as default (https://drive.google.com/folderview?id=0B6Xdg3_9Of5rME5MZHBaNHMySDQ) Any icon in the list that is not native Pixel icon, you don't have to use, like my Photoscan icon or News and Weather icon.

- Determine which app is the file explorer/downloads, settings, Phone, messaging, email and browser, and apply the round icons (especially on Samsung devices)

- BUG: Photoscan icon is missing shadow, Google Street view icon does not look quite native (the G is in the wrong place), icon is not applied to Google Camera and Google Play Games, Voice Search is given the wrong icon, and YouTube Music doesn't need white background

- When press holding on the home button on Lawnchair or on any app, regardless of Android Lollipop or Marshmallow feature, open the Google Assistant console. (I did it only with the Nova Launcher, and I have a Lollipop device. Check https://plus.google.com/+DondreJohnsonScholeggoKCM10/posts/8gpEnscXvnK and https://plus.google.com/+DondreJohnsonScholeggoKCM10/posts/AM7Gru61Zs5)

- Allow landscape rotation

- Allow option for search bar to be persistent (to be seen on any home screen, like the Pixel C Launcher)

- Always show weather widget when search bar is not widescreen

- Like in Nova Launcher, show app shortcuts for apps that support it (remember, I have a Lollipop device, and it works)

- Ability to edit app icon to Traditional, Pixel, icon pack, or custom from gallery apps, like Google Drive or Google Photos

- Ability to enable recent apps in drawer

- Ability to enable night mode effect on app drawer and/or app folders

- Show notification access in Launcher settings.

-Make badge color correspond to app icon color, like in Android O

- BUG: Some notification badges don't show on some apps, like Google Play Store when I downloaded a new app.

- BUG: The notification badges are overlapping on the app. It should be in the top right corner, not necessarily overlapping the corner, like on Android O

- Ability to edit animation when opening and closing an app, like in Nova Launcher

- When selecting the Google app, redirect to Google Now page instead of opening Google app in a new window

- BUG: when in overview, apps and widgets are able to open. This would be a problem if a page is full of stuff

- BUG: When renaming a folder, Lawnchair crashes

- BUG: When opening app drawer, the notification bar background doesn't change

- BUG: When scaling icons and text, it does not have effect on items in folder

- Allow users to edit icon that is on a home screen

- Allow users to choose which home page they want to be primary (put that in settings, because putting that option in overview doesn't make it look Pixel Launcher-like)

**Comment by TokedUp** [comment]
Dock app icons are smaller than all other icons in drawer

**Comment by deletescape** [comment]
@TokedUp There is an XDA Thread already
@Dondrejohnson5  Keep in mind that most developers would like to have single issues per request because with a list like this it is really hard to keep track of progress.
Some of your requests already have open issues associated with them. Additionally some of your requests are pretty cryptic or describe features which Lawnchair already has.

I'll never implement something I personally do not like, or I think is a too big impact on performance, but thanks a lot for your suggestions.

**Comment by Dondrejohnson5** [comment]
Ok. It's just that I want all my issues in one thread, so that every time I spot an issue, I won't have to keep making new threads, which is time consuming.
Also, if I wasn't clear on some points, tell me which ones I need to explain
Suggestion: If you don't like a feature I explained, at least give users an option to toggle it on or off.

**Comment by deletescape** [comment]
Closing this issue as the creator of this is being a d*ck. You actually just managed to make me mad on the internet (which is pretty hard). Read our conversation again. I am asking you to split your issue into multiple ones (which would be like 5 minutes of work for you) because this would save me atleast 1h of work. 

If you don't get it yet, I'm working 24h per week on this project, and I invest a lot of time in this, for **FREE**. I don't have to do this, I want to. So, you could now be nice and accept my tiny request to split it up, or you can be a d*ick and act like this is your Launcher and you're paying me for this work. 

You're not the one making the rules here. I am. I am also the one who decides which features to implement and which not.

!rant off

You have a second chance to first look if there are already existing threads for your issues or open new issues for each request.
