### ISSUE TITLE
Landscape mode bug

### ISSUE THREAD

**Issue by edwaine** [Deletescape-Media/Lawnchair#574]
I am currently using your latest version 1.1.0.1191 on Android 8 Oreo and here is the image of the launcher in landscape mode in comparison with the Pixel Launcher:

Home Screen:

Lawnchair App:
![Lawnchair Home Screen](https://dl2.pushbulletusercontent.com/hs8KWPQf0ZoRpscnrvqMuLCGXi6ENik3/Screenshot_20170823-025929.png)

Pixel Launcher:
![Pixel Home Screen](https://dl2.pushbulletusercontent.com/IYnvcAhEpKzlNLmLfMp153FHbTcPBeRp/Screenshot_20170823-033054.png)

App Drawer:

Lawnchair App:
![Lawnchair App Drawer](https://dl2.pushbulletusercontent.com/XvQf4iVqdXSIIHn4trNkzXR1JrTYy2Io/Screenshot_20170823-034139.png)

Pixel Launcher:
![Pixel App Drawer](https://dl2.pushbulletusercontent.com/oYKKFqWeHPx8ptMtpWJvdyM0KAHOe3tF/Screenshot_20170823-033101.png)  

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shiva39** [comment]
Where is link for new version

**Comment by edwaine** [comment]
@shiva39 You can download the latest version here:
https://lawnchairmirror.duckdns.org/

**Comment by edwaine** [comment]
@deletescape I've just tried your latest version 1.1.0.119 and the landscape bug is gone. Thanks! You can now close this one.

**Comment by shiva39** [comment]
Where is the link for new version


On Aug 23, 2017 1:16 PM, "edwaine" <notifications@github.com> wrote:

@deletescape <https://github.com/deletescape> I've just tried your latest
version 1.1.0.119 and the landscape bug is gone. Thanks! You can now close
this one.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Deletescape-Media/Lawnchair/issues/574#issuecomment-324249021>,
or mute the thread

**Comment by edwaine** [comment]
@shiva39 
Please go to that site:
https://lawnchairmirror.duckdns.org/
deletescape always updates his project very often. :)

**Comment by suphon-t** [comment]
Should be fixed in 1.1.0.1194

**Comment by edwaine** [comment]
@paphonb Yes, the landscape bug is indeed fixed. :)
I've tried it on my Pixel, Nexus 5X & Android One G1(Seed).
