### ISSUE TITLE
Weather is not right and double tap to sleep doesn't work

### ISSUE THREAD

**Issue by adnankaize** [Deletescape-Media/Lawnchair#627]
Hi, I just downloaded the launcher and when I enable weather. The right temperature is not show. It shows 23 while the temperature is 26 and only if I click it, an app opens showing the right weather. And if I set the weather Google Awareness API. No weather is shown at all.

Another issue is that, in my LG G6, I can double tap the screen to turn it on and off. But now, it only turns on the screen and not off.

Please Help.
Thank You

**Comment by nyancrimew** [comment]
Google awareness as weather provider only works if Location Access is granted to Lawnchair and Location (GPS) is enabled. Inaccuracies/differences from the weather in google now are due to different weather providers and not a bug, we can't change that.

Lawnchair doesn't yet have a double tap to sleep feature, but we are already tracking progress for that in another issue.
