### ISSUE TITLE
[Feature Request] Opt-out of App Telemetry/Crash Reporting

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#691]
I noticed Lawnchair sending data to Microsoft Azure servers. I'm guessing this is some sort of device telemetry and crash reporting. Please confirm what is being sent and add a setting for the user to opt-out.

**Comment by guest4711** [comment]
In some countries, e. g. germany, you need an 'opt in' to allow this type of sampling data... So please make it optional and place a hint on first start (e.g. where the changelog is displayed).

**Comment by divadsn** [comment]
To be honest, I still don't get why Germans are so overconcerned about sending anonymous data to a server for analytics, so in the meanwhile I can give you a good instructions on how to protect yourself:

![Aluhut Anleitung](http://www.schindluder.net/wp-content/uploads/2014/08/aluhut_anleitung.png.client.x675.png)

Also you can look into the source code for anything privacy related, so you will know what's actually submitted for analysis.

**Comment by fonix232** [comment]
We are using Microsoft's Azure Mobile for very basic telemetry - the app checks in basic information to see our target demographics, all of them are non-invasive and do not contain any information that can be used for personal identification.

The included information are:

 - Device manufacturer and model
 - App version
 - Android version
 - Country (based on the IP address, at the moment about 50% of the users' countries cannot be determined)
 - Session count (how many times the app is opened, etc.)

This telemetry is for us to see which countries use the app the most, which versions fixed, introduced or re-introduced issues, and of course, crash logs for issues.

@guest4711 the kind of telemetry we are doing does not fall under the german DPA laws, since it requires apps to abide by it if they publish personal information. Since NO personal information or any kind of identifier is established (apart from the instance-specific Azure ID of the device, so that an issue chain can be tracked - this ID is generated during install, and removal of the app will result in a new ID if reinstalled) that can pinpoint a specific user, this does not fall under the DPA laws you mention.

**Comment by guest4711** [comment]
Even google supports resetting the advertising id without the need to uninstall and reinstall anything.

**Comment by fonix232** [comment]
Last time I checked, the Azure Mobile SDK provides no way to reset the ID, though I have to admit that I never checked for this.

However since we're not using the data for anything else than bettering Lawnchair (i.e. we're not selling anything that comes in, especially since it has no market value), and we're not receiving any personal information.

For the time being, we will leave this as-is - a little telemetry does not hurt anyone, especially since most users are unable to report problems in a developer-comprehensible format, where such logs are the main sources of diagnostics and troubleshooting.

**Comment by ghost** [comment]
I suppose you don't mind if the project is forked to remove the telemetry then?

**Comment by divadsn** [comment]
![Shia LaBeouf "Just Do It"](https://media.giphy.com/media/Z0dvuZszc3r3i/giphy.gif)

@HeatedTea there is no need to fork, just clone it locally and remove it :roll_eyes:
