### ISSUE TITLE
Feature Request: Add empty homescreen

### ISSUE THREAD

**Issue by ghost** [Deletescape-Media/Lawnchair#699]
Allows better support with other theming apps like KLWP and KWGT.

Android version: 8.0.0
Launcher version: 1.1.0.1244

**Comment by divadsn** [comment]
Why not add the widget on a new site instead? Never seen this ability on a launcher before.

**Comment by fonix232** [comment]
@divadsn actually most manufacturer Launcher3 forks (Sony, Samsung, LG) support having multiple empty pages.

**Comment by divadsn** [comment]
So add or no add, @fonix232? :P

**Comment by callmemulo** [comment]
what is the reason behind empty pages?

**Comment by noodlejetski** [comment]
hi, I'm not sure if there's any point to comment on a closed issue, but I've been missing that option in Lawnchair and my github search has brought me here and I haven't seen any open issues about it.

having multiple empty homescreens is very useful for more complicated KLWP setups, that rely on swiping left and right to change layout or move panels around.

as an example, here's a screen recording of the setup I've made a while ago: https://gfycat.com/waterloggedartisticjunco
the little panels are actually a part of the live wallpaper, not standalone widgets, and they're moving around because of the wallpaper "scrolling" while switching homescreens. it's achieved by using a 3 homescreen setup, with the rightmost of them being empty. there are tons of other KLWP presets that completely transform the homescreen when swiping, and they all rely on that option, which currently makes them impossible to use with Lawnchair because of that.
