### ISSUE TITLE
Weather not consistently updating. 

### ISSUE THREAD

**Issue by Mackerel71** [Deletescape-Media/Lawnchair#701]
## Description
Weather not consistently updating throughout the day as the weather changes. I've tried both Weather Providers with similar results. 

## Expected Behavior
1. OpenWeatherMap API - Weather should update as it changes throughout the day based on the city, state, and zip code entered in the settings. 

2. GoogleAwareness API- Weather should update as it changes throughout the day based upon the location. 

Note, I do not know the frequency that it should update. 

## Actual Behavior
It is hit or miss as to whether the weather updates or not.

## Steps to Reproduce
1. Turn weather setting on and choose a Weather Provider. 
2. Reboot phone to start with a fresh slate. 
3. Verify weather using multiple weather apps. 
4. Monitor throughout the day and record results. 

## Environment
* Device: LG G6
* Android version: 7.0
* Launcher version: 1.1.0.1243
* Rom: Stock

## Notes
I do know that with Google's official Pixel Launcher that if you tap on the weather widget to open the weather app, the weather will update on the widget if they are not in sync. I do not know the frequency of the weather updates for that Launcher either.

**Comment by fonix232** [comment]
The official Pixel Launcher uses different weather information methods, and thus can update differently.

As for the Google Awareness weather provider... Unfortunately Google made it so that even if the location changes considerably, weather only updates if the temperature difference between current reported and last known (i.e. displayed) is 3 degrees or higher. So you can easily get on a plane in sunshine, 18°C, and arrive in a tropical storm, 17°C, and it won't update.

**Comment by divadsn** [comment]
https://github.com/Deletescape-Media/Lawnchair/wiki/FAQ#why-is-the-weather-different-from-the-one-on-google-now
