### ISSUE TITLE
Animated clock icon not working for clock with package name com.android.deskclock

### ISSUE THREAD

**Issue by ygorigor** [Deletescape-Media/Lawnchair#706]
* Device: Redmi 3S
* Android version: 7.1.2
* Launcher version: 1.1.0.1243
* Rom: Custom: XPerience 11.1.2

**Comment by fonix232** [comment]
The template is not there for you to ignore. Fill it out properly please.

**Comment by guest4711** [comment]
@fonix232 No template visible/available when using FastHub.

**Comment by fonix232** [comment]
@guest4711 I believe it isn't the repo maintainers' issue that someone can't use a client that actually works. My point still stands, either use the template or GTFO.

Besides, since I receive e-mail updates about all activities, I can see that @ygorigor has had the template, then decided to remove it and keep only the device info, providing no information about his issue whatsoever.

**Comment by guest4711** [comment]
Using FastHub or some other mobile clients for github you even don't see there is any template... And how should they know that they are missing it if they are new to github?

**Comment by divadsn** [comment]
@guest4711 that's still not an excuse, nag the developer of FastHub and not us or GitHub.

Also, you can copy the content of the issue template from the repo :wink:
https://raw.githubusercontent.com/Deletescape-Media/Lawnchair/alpha/.github/ISSUE_TEMPLATE.md
