### ISSUE TITLE
Wallpaper gets shifted

### ISSUE THREAD

**Issue by marcinciarka** [Deletescape-Media/Lawnchair#726]
## Description
After couple of hours the wallpaper gets shifted and it's not looking good with blur options.

## Expected Behavior
1. Set wallpaper would stay in place (it's a wallpaper with no parallax effect).

## Actual Behavior
After couple of hours using the lawnchair (using apps and going back to home) the wallpaper gets enlarged and shifted. Please check the screenshot included.

## Steps to Reproduce

1. Set fitting wallpaper (no parallax)
2. After couple of hours the wallpaper get's shifted
3. Sadness

## Environment
* Device: Xiaomi Mi 6
* Android version: 7.0.1
* Launcher version: latest
* Rom: MIUI polska

![image](https://user-images.githubusercontent.com/5095527/30475252-802ae0fe-9a06-11e7-85d5-5c8e90285605.png)

**Comment by LinuxLlama** [comment]
Are you using Google Wallpaper's daily wallpaper option?

**Comment by marcinciarka** [comment]
No, im using a wallpaper manualny set in the options.

**Comment by divadsn** [comment]
It's a common issue, no matter which device and ROM.

Also, it's happening with any other Launcher, so the only thing we could try is to re-blur after refresh.

**Comment by Tooniis** [comment]
What actually happens is that when an app rotates to landscape mode, the wallpaper gets shifted that way, and then when you close the app and return to portrait mode, the wallpaper stays as it is instead of shifting back to its original position. At least that is what is happening on my phone (which is a Xiaomi Mi Note 2 with MIUI Global Stable 9.2.1.0, Android 7.0). I hope this bug gets fixed soon. 
@divadsn I've tried many launchers, including Nova and Action, and this issue never exists in them.
