### ISSUE TITLE
Not able to install Travis-198.apk

### ISSUE THREAD

**Issue by Lightshadow226** [Deletescape-Media/Lawnchair#77]
I already have Travis-183.apk installed, and I downloaded the new version (Travis-198.apk) today, and when I install it, it says "App not installed".

Does anyone know how I can install the new version? (Ideally without having to delete my current launcher)

Thank you.

![image](https://user-images.githubusercontent.com/7082956/27608126-41c2f25c-5b54-11e7-8b6d-4bf7a1ab0a6e.png)

**Comment by deletescape** [comment]
As you can read in the changelog of this release there is currently an issue with building on travis which causes signature changes, so you actually will have to uninstall and reinstall. If you are rooted and want to keep your setup you can simply use titanium backup to backup and restore the data

**Comment by Wolfium** [comment]
Understand, it is a shame for not rooted users like me.

Most because it is an infrastructure issue, not an app limitation.

Hope anyone find a workaround for not rooted users.
Would be too much to ask for a basic export and import file feature?

Keep up your awesome work, use it daily and feels great on a Nexus 5 with marshmallow Android

**Comment by Wolfium** [comment]
I just wondering if setting (backed up by google as default) will be restored on this new version install.

I really like the app and to be updated as much as possible.
But it took me a while to arrange icons same as google official launcher before changing.

Any one know it setting behavior will be kept or lost on uninstalling and installing new version?

Thanks in advance for any feedback.
Regards

Wolfium
