### ISSUE TITLE
Blur effects not working

### ISSUE THREAD

**Issue by zahanehsan** [Deletescape-Media/Lawnchair#805]
Blur effects not working with google wallpapers app
## Description

When I set a daily wallpaper using wallpapers app, blur effects do not work.
## Steps to Reproduce

1.Enable blur effects.
2.Change wallpaper and turn on daily wallpapers and apply it.

## Environment

* Device: Redmi note 4 (mido)
* Android version:7.1.1
* Launcher version:1.0.1063
* Rom:lineageos official

## Logcat

```
your log here
```

**Comment by ghost** [comment]
Hello. This is due to the fact that Android consider this as an animated wallpaper, apps like Muzei can't get a blur effect. Launcher like Evie Launcher for examples have a blur effect in the App Drawer. It doesn't work when you use app such as Muzei because Android sees it as a live/animated wallpaper. :)
