### ISSUE TITLE
Landscape orientation on tablets.

### ISSUE THREAD

**Issue by Timbets** [Deletescape-Media/Lawnchair#824]
Launcher defaults to portrait on tablets like Nexus 10. Enabling rotation in lawnchair settings fixes this. On Pixel launcher and basically every other launcher that is not needed. So normally pixel launcher would stay in landscape unless you allow it to rotate to portrait. With Lawnchair it is portrait unless you allow it to rotate. So you cant have launcher homescreen locked to landscape and allow rotation in other apps. Now you must lock it to landscape on system level.

**Comment by fonix232** [comment]
I believe this is because Lawnchair's main activity does not rely on device-supplied default orientation (i.e. landscape on landscape-designed tablets, portrait on portrait-designed tablets, etc.), but uses fixed portrait and landscape options:

https://github.com/Deletescape-Media/Lawnchair/blob/alpha/app/src/main/java/ch/deletescape/lawnchair/Launcher.java#L385

@deletescape I might look at this during the weekend unless it is fixed by then :)

**Comment by divadsn** [comment]
Ping
