### ISSUE TITLE
Adding Pixel 2 folder anims to Lawnchair

### ISSUE THREAD

**Issue by Guema** [Deletescape-Media/Lawnchair#878]
## Description

Enhancement : Make app folders opening/closing animations match Pixel 2 launcher ones. 

## Expected Behavior

The pixel 2 launcher animation is somewhat a zoom, making app icons zoom at the same time of the folder while being expanded. It is really complicated to explain, but what to keep in mind is that Pixel 2 launcher animation show app icons the folder contains while the animation is playing.

## Actual Behavior

Lawnchair animation is working well, there is no bug, but when clicking folder, the anim will draw a new white block, playing an expanding animation, and then, when the animation is completed, display the icons it contains. Try to see the difference. It is in fact based on the animation of Pixel Launcher 1.

This is not a must have feature, lol (absolutly not in fact), just fresh and new stylish way to display it. I have absolutely no idea what it represents in working time, so, i just let it here.

## Steps to Reproduce

1. Create a folder by drag and dropping an app in another
2. Open the folder.
3. Close the folder.
4. Compare to Launcher 2 animation.
5. Find that it is not the same.

## Environment

* Device: Nexus 5X
* Android version: 8.0.0
* Launcher version: 1427
* Rom: OPR4.170623.009

**Comment by OvermindDL1** [comment]
Probably the easiest way to implement it is just to take a snapshot of the app menu scrolled to the top (since that is how it naturally opens) and hold on to it, displaying it scaling up until the full app menu is loaded and swapped to at the end of the animation (scaling the animation so it does not end until the app icons are loaded).  This would, however, prevent people from tapping on an icon 'while' it is scaling up to try to load it as some people would naturally try to do, but that could be worked around by capturing the input events and running them once the app drawer loads.

**Comment by divadsn** [comment]
Already working on these.

**Comment by Guema** [comment]
Do not close then, guys !
It will prevent some ppl to duplicate if you let it open until it is here ^^
(At least it has a chance, i checked it fast, and didn't see any corresponding one myself)

btw, thanks and congrats for ur awesome work !

**Comment by Joccob** [comment]
@divadsn The folder open animation still doesn't look like what's in Pixel 2. Is it possible to reopen this issue?

**Comment by divadsn** [comment]
@Joccob v2 is work in progress
