### ISSUE TITLE
Weather disappear when data/WiFi is kept off overnight

### ISSUE THREAD

**Issue by KapilFaujdar** [Deletescape-Media/Lawnchair#898]
When internet is kept disconnected (WiFi/Data) overnight, weather disappear in the morning (just blank space). I always need to restart Launcher to get it back.

* Device: Moto G5 Plus
* Android version: 7.0
* Launcher version: 1.1.0.1427
* Rom: Stock

**Comment by AxiK101** [comment]
If you are offline for some hours, the weather reverts to calendar widget, go online and at first refresh weather reappears. It's normal functionality

**Comment by KapilFaujdar** [comment]
But it doesn't show calendar either. Now i am online for more than an hour and there is nothing being shown in that blank space.

**Comment by aleksandar-stefanovic** [comment]
It looks somewhat broken, like this:

![screenshot](https://user-images.githubusercontent.com/6058082/32435152-74ea050a-c2e0-11e7-86c8-8231ea0e91be.png)


This is taken from the latest Play Store release. Notice that there is the date format where the date would otherwise be (it displays "YYYY MMMM D", localized)

**Comment by anishmworld** [comment]
Same problem here, but even with always on mobile and Wi-Fi data. I'm usually always connected to the internet but sometimes the weather is replaced by blank space anyway.

**Comment by EBendinelli** [comment]
Same issue here. When I'm on data I can see the same thing as @aleksandar-stefanovic and then it goes back to just displaying time and date. If I long press it I can quickly see a big yellow "error'.

It's a fresh install on a fresh LineageOS with openGApps pico if this helps (mybe I'm missing dependencies?). It was working fine ofr one day and hasn't worked any more since then.
